const HIRAGANA = [
  // Vowels
  {char:'あ',romaji:'a',thai:'อา',type:'vowel',mnemonic:'เหมือนคนกำลัง อ้าปาก แล้วพูดว่า "อาาาา" 😮',example:'あめ (ame) = ฝน'},
  {char:'い',romaji:'i',thai:'อิ',type:'vowel',mnemonic:'เหมือนเลข 1 สองอัน (い) ใครที่ยืน "อิอิ" อยู่สองคน 🧍🧍',example:'いぬ (inu) = สุนัข'},
  {char:'う',romaji:'u',thai:'อุ',type:'vowel',mnemonic:'เหมือนปากที่ยื่นออกมาพูดว่า "อุ" ปากจู๋ 😗',example:'うみ (umi) = ทะเล'},
  {char:'え',romaji:'e',thai:'เอ',type:'vowel',mnemonic:'เหมือนเสาไฟฟ้า ตัว え มีขาค้ำยัน "เอ!" น่าจะตก 😱',example:'えき (eki) = สถานีรถไฟ'},
  {char:'お',romaji:'o',thai:'โอ',type:'vowel',mnemonic:'เหมือนคนนั่งยองๆ มองดูอะไร แล้วอ้า "โอ้โห!" 😲',example:'おかあ (okaa) = แม่'},
  // K row
  {char:'か',romaji:'ka',thai:'คะ',type:'k',mnemonic:'ตัวか เหมือนนักกายกรรม "คะ!" ที่กำลังหมุนตัว 🤸',example:'かみ (kami) = ผม'},
  {char:'き',romaji:'ki',thai:'คิ',type:'k',mnemonic:'ตัวき เหมือนต้นไม้ที่มีกิ่งก้าน "คิ" เหมือน "tree" ในภาษาญี่ปุ่น 🌳',example:'き (ki) = ต้นไม้'},
  {char:'く',romaji:'ku',thai:'คุ',type:'k',mnemonic:'ตัวく เหมือนปากนกที่อ้าค้างไว้ "คุ!" นกกำลังร้อง 🐦',example:'くも (kumo) = เมฆ'},
  {char:'け',romaji:'ke',thai:'เค',type:'k',mnemonic:'ตัวけ เหมือนคนยืนแบกของ "เค" นะแบกหนักมาก 😤',example:'けむり (kemuri) = ควัน'},
  {char:'こ',romaji:'ko',thai:'โค',type:'k',mnemonic:'ตัวこ เหมือนเลข 2 นอนราบ "โค" ตัวอักษรนอนสองชั้น 💤',example:'こねこ (koneko) = ลูกแมว'},
  // S row
  {char:'さ',romaji:'sa',thai:'ซะ',type:'s',mnemonic:'ตัวさ เหมือนคนนั่งดื่มกาแฟ "ซะ!" พักก่อนนะ ☕',example:'さくら (sakura) = ดอกซากุระ'},
  {char:'し',romaji:'shi',thai:'ชิ',type:'s',mnemonic:'ตัวし เหมือนขอเกี่ยวที่งอขึ้น "ชิ" งอขึ้นเหมือนตะขอ 🪝',example:'しろ (shiro) = สีขาว'},
  {char:'す',romaji:'su',thai:'ซุ',type:'s',mnemonic:'ตัวす เหมือนอ่างน้ำวน "ซุ" น้ำวนๆ 🌀',example:'すし (sushi) = ซูชิ'},
  {char:'せ',romaji:'se',thai:'เซ',type:'s',mnemonic:'ตัวせ เหมือนโต๊ะที่มีขาสั้น "เซ" โต๊ะเซไม่มั่นคง 🪑',example:'せんせい (sensei) = ครู'},
  {char:'そ',romaji:'so',thai:'โซ',type:'s',mnemonic:'ตัวそ เหมือนสายฟ้าโค้ง "โซ" ฟ้าแลบโซ่ซ่า ⚡',example:'そら (sora) = ท้องฟ้า'},
  // T row
  {char:'た',romaji:'ta',thai:'ตะ',type:'t',mnemonic:'ตัวた เหมือนคนตีกอล์ฟ "ตะ" แกว่งไม้กอล์ฟ ⛳',example:'たまご (tamago) = ไข่'},
  {char:'ち',romaji:'chi',thai:'ชิ',type:'t',mnemonic:'ตัวち เหมือนตัวเลข 6 ที่พลิก "ชิ" เลข 6 กลับหัว 6️⃣',example:'ちず (chizu) = แผนที่'},
  {char:'つ',romaji:'tsu',thai:'ซึ',type:'t',mnemonic:'ตัวつ เหมือนคลื่นทะเล "ซึ" คลื่นโค้งๆ 🌊',example:'つき (tsuki) = พระจันทร์'},
  {char:'て',romaji:'te',thai:'เต',type:'t',mnemonic:'ตัวて เหมือนเส้นที่ห้อยลงมา "เต" เส้นห้อยน้อย 🪢',example:'てがみ (tegami) = จดหมาย'},
  {char:'と',romaji:'to',thai:'โต',type:'t',mnemonic:'ตัวと เหมือนกุญแจ "โต" กุญแจใบโตๆ 🗝️',example:'とり (tori) = นก'},
  // N row
  {char:'な',romaji:'na',thai:'นะ',type:'n',mnemonic:'ตัวな เหมือนปลาที่ว่ายน้ำ "นะ" ปลาน่ารักๆ 🐟',example:'なまえ (namae) = ชื่อ'},
  {char:'に',romaji:'ni',thai:'นิ',type:'n',mnemonic:'ตัวに เหมือนเข็มทิศ "นิ" ชี้ทิศ 🧭',example:'にほん (nihon) = ญี่ปุ่น'},
  {char:'ぬ',romaji:'nu',thai:'นุ',type:'n',mnemonic:'ตัวぬ เหมือนเส้นบะหมี่ที่พันกัน "นุ" บะหมี่กึ๋ยน 🍜',example:'ぬいぐるみ (nuigurumi) = ตุ๊กตา'},
  {char:'ね',romaji:'ne',thai:'เน',type:'n',mnemonic:'ตัวね เหมือนแมวที่ขดตัวนอน "เน" แมวเนียๆ 🐱',example:'ねこ (neko) = แมว'},
  {char:'の',romaji:'no',thai:'โน',type:'n',mnemonic:'ตัวの เหมือนเส้นวนรูปตัว o "โน" วนเป็นวงกลม ⭕',example:'のり (nori) = สาหร่าย'},
  // H row
  {char:'は',romaji:'ha',thai:'ฮะ',type:'h',mnemonic:'ตัวは เหมือนคนที่หัวเราะ "ฮะฮะ" ปากอ้ากว้าง 😄',example:'はな (hana) = ดอกไม้'},
  {char:'ひ',romaji:'hi',thai:'ฮิ',type:'h',mnemonic:'ตัวひ เหมือนตัว B ที่ถูกกระชากออก "ฮิ" B ขาดกลาง 😅',example:'ひと (hito) = คน'},
  {char:'ふ',romaji:'fu',thai:'ฟุ',type:'h',mnemonic:'ตัวふ เหมือนใบพัด "ฟุ" พัดลมหมุนๆ 🌀',example:'ふゆ (fuyu) = ฤดูหนาว'},
  {char:'へ',romaji:'he',thai:'เฮ',type:'h',mnemonic:'ตัวへ เหมือนหลังคาบ้าน "เฮ" บ้านหลังคาแหลม 🏠',example:'へや (heya) = ห้อง'},
  {char:'ほ',romaji:'ho',thai:'โฮ',type:'h',mnemonic:'ตัวほ เหมือนซานตาคลอส "โฮโฮโฮ" ยืนถือของขวัญ 🎅',example:'ほし (hoshi) = ดาว'},
  // M row
  {char:'ま',romaji:'ma',thai:'มะ',type:'m',mnemonic:'ตัวま เหมือนมดที่มีหนวด "มะ" มดแมลง 🐜',example:'まち (machi) = เมือง'},
  {char:'み',romaji:'mi',thai:'มิ',type:'m',mnemonic:'ตัวみ เหมือนคนนั่งมองน้ำ "มิ" สะท้อน 🪞',example:'みず (mizu) = น้ำ'},
  {char:'む',romaji:'mu',thai:'มุ',type:'m',mnemonic:'ตัวむ เหมือนวัวที่หันหัวมา "มุ" หน้าวัว 🐄',example:'むし (mushi) = แมลง'},
  {char:'め',romaji:'me',thai:'เม',type:'m',mnemonic:'ตัวめ เหมือนตา "เม" ตาใหญ่โตมองดู 👁️',example:'めだか (medaka) = ปลาเมดากะ'},
  {char:'も',romaji:'mo',thai:'โม',type:'m',mnemonic:'ตัวも เหมือนตะขอสองอัน "โม" ตะขอคู่ 🪝🪝',example:'もり (mori) = ป่า'},
  // Y row
  {char:'や',romaji:'ya',thai:'ยะ',type:'y',mnemonic:'ตัวや เหมือนรถม้าที่วิ่ง "ยะ" เร็วๆ 🏇',example:'やま (yama) = ภูเขา'},
  {char:'ゆ',romaji:'yu',thai:'ยุ',type:'y',mnemonic:'ตัวゆ เหมือนปลาที่ว่ายน้ำ "ยุ" ปลาตัวโค้ง 🐠',example:'ゆき (yuki) = หิมะ'},
  {char:'よ',romaji:'yo',thai:'โย',type:'y',mnemonic:'ตัวよ เหมือนไม้พาย "โย" กวนน้ำ 🚣',example:'よる (yoru) = กลางคืน'},
  // R row
  {char:'ら',romaji:'ra',thai:'ระ',type:'r',mnemonic:'ตัวら เหมือนมีดโกนที่งอ "ระ" ระวังคม 🪒',example:'らいねん (rainen) = ปีหน้า'},
  {char:'り',romaji:'ri',thai:'ริ',type:'r',mnemonic:'ตัวり เหมือนเชือกผูกโบว์สองอัน "ริ" โบว์สวยๆ 🎀',example:'りんご (ringo) = แอปเปิ้ล'},
  {char:'る',romaji:'ru',thai:'รุ',type:'r',mnemonic:'ตัวる เหมือนงูที่ขดตัว "รุ" งูขดๆ 🐍',example:'るすばん (rusuban) = เฝ้าบ้าน'},
  {char:'れ',romaji:'re',thai:'เร',type:'r',mnemonic:'ตัวれ เหมือนคนโค้งคำนับ "เร" ก้มหัวไหว้ 🙇',example:'れい (rei) = ศูนย์'},
  {char:'ろ',romaji:'ro',thai:'โร',type:'r',mnemonic:'ตัวろ เหมือนถนนโค้งๆ "โร" ขับรถโรลๆ 🛣️',example:'ろうか (rouka) = ทางเดิน'},
  // W row
  {char:'わ',romaji:'wa',thai:'วะ',type:'w',mnemonic:'ตัวわ เหมือนตัว れ แต่ไม่มีหาง "วะ" เหมือน れ ที่ตัดหาง ✂️',example:'わたし (watashi) = ฉัน'},
  {char:'を',romaji:'wo',thai:'โว',type:'w',mnemonic:'ตัวを อ่านว่า "โว" แต่จริงๆ ออกเสียงเหมือน お ใช้เป็น particle เท่านั้น 🔤',example:'ほんを (hon wo) = หนังสือ (กรรม)'},
  {char:'ん',romaji:'n',thai:'น',type:'special',mnemonic:'ตัวん เหมือนหนอนที่ขดตัว "น" เหมือนหนอนตัวน้อย 🐛',example:'にほん (nihon) = ญี่ปุ่น'},
  // Dakuten
  {char:'が',romaji:'ga',thai:'กะ',type:'dakuten',mnemonic:'か + เครื่องหมายทำให้เป็น が เสียงหนักขึ้น "กะ" 💪',example:'がっこう (gakkou) = โรงเรียน'},
  {char:'ぎ',romaji:'gi',thai:'กิ',type:'dakuten',mnemonic:'き + dakuten = ぎ เสียง "กิ" หนักขึ้น 🔊',example:'ぎんこう (ginkou) = ธนาคาร'},
  {char:'ぐ',romaji:'gu',thai:'กุ',type:'dakuten',mnemonic:'く + dakuten = ぐ เสียง "กุ" นุ่มขึ้น 🐋',example:'ぐあい (guai) = อาการ'},
  {char:'げ',romaji:'ge',thai:'เก',type:'dakuten',mnemonic:'け + dakuten = げ "เก" หนักขึ้น 🎮',example:'げんき (genki) = สบายดี'},
  {char:'ご',romaji:'go',thai:'โก',type:'dakuten',mnemonic:'こ + dakuten = ご เหมือน "โก" ล่อ 🌟',example:'ごはん (gohan) = ข้าว'},
  {char:'ざ',romaji:'za',thai:'ซะ',type:'dakuten',mnemonic:'さ + dakuten = ざ เสียง "ซะ" นุ่มขึ้น 🌺',example:'ざっし (zasshi) = นิตยสาร'},
  {char:'じ',romaji:'ji',thai:'จิ',type:'dakuten',mnemonic:'し + dakuten = じ เสียง "จิ" นุ่มขึ้น 🦋',example:'じかん (jikan) = เวลา'},
  {char:'ず',romaji:'zu',thai:'ซุ',type:'dakuten',mnemonic:'す + dakuten = ず "ซุ" เป็นเสียงก้อง 🎵',example:'ずっと (zutto) = ตลอดไป'},
  {char:'ぜ',romaji:'ze',thai:'เซ',type:'dakuten',mnemonic:'せ + dakuten = ぜ "เซ" เสียงก้อง 💫',example:'ぜんぶ (zenbu) = ทั้งหมด'},
  {char:'ぞ',romaji:'zo',thai:'โซ',type:'dakuten',mnemonic:'そ + dakuten = ぞ "โซ" เสียงก้อง 🌙',example:'ぞう (zou) = ช้าง'},
  {char:'だ',romaji:'da',thai:'ดะ',type:'dakuten',mnemonic:'た + dakuten = だ "ดะ" เสียงก้อง 🥁',example:'だいじょうぶ (daijoubu) = ไม่เป็นไร'},
  {char:'ぢ',romaji:'di',thai:'ดิ',type:'dakuten',mnemonic:'ち + dakuten = ぢ "ดิ" เสียงก้อง (ใช้น้อย) 📝',example:'はなぢ (hanadi) = เลือดกำเดา'},
  {char:'づ',romaji:'du',thai:'ดุ',type:'dakuten',mnemonic:'つ + dakuten = づ "ดุ" เสียงก้อง (ใช้น้อย) 📝',example:'つづく (tsuzuku) = ต่อเนื่อง'},
  {char:'で',romaji:'de',thai:'เด',type:'dakuten',mnemonic:'て + dakuten = で "เด" เสียงก้อง 🎸',example:'でんしゃ (densha) = รถไฟ'},
  {char:'ど',romaji:'do',thai:'โด',type:'dakuten',mnemonic:'と + dakuten = ど "โด" เสียงก้อง 🚪',example:'どこ (doko) = ที่ไหน'},
  {char:'ば',romaji:'ba',thai:'บะ',type:'dakuten',mnemonic:'は + dakuten = ば "บะ" เสียงก้อง 🏀',example:'ばしょ (basho) = สถานที่'},
  {char:'び',romaji:'bi',thai:'บิ',type:'dakuten',mnemonic:'ひ + dakuten = び "บิ" นุ่มขึ้น 🐝',example:'びょういん (byouin) = โรงพยาบาล'},
  {char:'ぶ',romaji:'bu',thai:'บุ',type:'dakuten',mnemonic:'ふ + dakuten = ぶ "บุ" เสียงก้อง 🐷',example:'ぶた (buta) = หมู'},
  {char:'べ',romaji:'be',thai:'เบ',type:'dakuten',mnemonic:'へ + dakuten = べ "เบ" เสียงก้อง 🔔',example:'べんとう (bentou) = ข้าวกล่อง'},
  {char:'ぼ',romaji:'bo',thai:'โบ',type:'dakuten',mnemonic:'ほ + dakuten = ぼ "โบ" เสียงก้อง ⚫',example:'ぼくじょう (bokujou) = ฟาร์ม'},
  {char:'ぱ',romaji:'pa',thai:'ปะ',type:'dakuten',mnemonic:'は + handakuten (วงกลม) = ぱ "ปะ" เสียงชัดเจน 🎈',example:'ぱーてぃ (paati) = ปาร์ตี้'},
  {char:'ぴ',romaji:'pi',thai:'ปิ',type:'dakuten',mnemonic:'ひ + handakuten = ぴ "ปิ" เสียงชัดเจน 🎵',example:'ぴんく (pinku) = สีชมพู'},
  {char:'ぷ',romaji:'pu',thai:'ปุ',type:'dakuten',mnemonic:'ふ + handakuten = ぷ "ปุ" เสียงชัดเจน 💥',example:'ぷろ (puro) = โปร'},
  {char:'ぺ',romaji:'pe',thai:'เป',type:'dakuten',mnemonic:'へ + handakuten = ぺ "เป" เสียงชัดเจน 🖊️',example:'ぺん (pen) = ปากกา'},
  {char:'ぽ',romaji:'po',thai:'โป',type:'dakuten',mnemonic:'ほ + handakuten = ぽ "โป" เสียงชัดเจน 🫧',example:'ぽけっと (poketto) = กระเป๋า'},
  // Combination sounds
  {char:'きゃ',romaji:'kya',thai:'เคียะ',type:'combo',mnemonic:'き + ゃ = きゃ เสียงผสม "เคียะ" สั้นๆ 🔗',example:'きゃく (kyaku) = แขก/ลูกค้า'},
  {char:'きゅ',romaji:'kyu',thai:'เคียว',type:'combo',mnemonic:'き + ゅ = きゅ "เคียว" เสียงผสม 🎯',example:'きゅうり (kyuuri) = แตงกวา'},
  {char:'きょ',romaji:'kyo',thai:'เคียว',type:'combo',mnemonic:'き + ょ = きょ "เคียว" เสียงผสม 📚',example:'きょう (kyou) = วันนี้'},
  {char:'しゃ',romaji:'sha',thai:'ชะ',type:'combo',mnemonic:'し + ゃ = しゃ "ชะ" เสียงผสม 🌊',example:'しゃしん (shashin) = รูปถ่าย'},
  {char:'しゅ',romaji:'shu',thai:'ชุ',type:'combo',mnemonic:'し + ゅ = しゅ "ชุ" เสียงผสม 🎪',example:'しゅくだい (shukudai) = การบ้าน'},
  {char:'しょ',romaji:'sho',thai:'โชะ',type:'combo',mnemonic:'し + ょ = しょ "โชะ" เสียงผสม 🏪',example:'しょうがつ (shogatsu) = ปีใหม่ญี่ปุ่น'},
  {char:'ちゃ',romaji:'cha',thai:'ชะ',type:'combo',mnemonic:'ち + ゃ = ちゃ "ชะ" เสียงผสม ☕',example:'おちゃ (ocha) = ชา'},
  {char:'ちゅ',romaji:'chu',thai:'ชุ',type:'combo',mnemonic:'ち + ゅ = ちゅ "ชุ" เหมือน "จูบ" 💋',example:'ちゅうごく (chuugoku) = จีน'},
  {char:'ちょ',romaji:'cho',thai:'โชะ',type:'combo',mnemonic:'ち + ょ = ちょ "โชะ" เสียงผสม 🦋',example:'ちょっと (chotto) = นิดหน่อย'},
  {char:'にゃ',romaji:'nya',thai:'เนียะ',type:'combo',mnemonic:'に + ゃ = にゃ "เนียะ" เสียงแมว 🐱',example:'にゃんこ (nyanko) = น้องแมว'},
  {char:'にゅ',romaji:'nyu',thai:'เนียว',type:'combo',mnemonic:'に + ゅ = にゅ "เนียว" เสียงผสม 🥛',example:'にゅうがく (nyuugaku) = เข้าเรียน'},
  {char:'にょ',romaji:'nyo',thai:'เนียว',type:'combo',mnemonic:'に + ょ = にょ "เนียว" เสียงผสม 🌿',example:'にょろにょろ (nyoronyoro) = เลื้อยๆ'},
  {char:'ひゃ',romaji:'hya',thai:'เฮียะ',type:'combo',mnemonic:'ひ + ゃ = ひゃ "เฮียะ" เสียงผสม 💨',example:'ひゃく (hyaku) = หนึ่งร้อย'},
  {char:'ひゅ',romaji:'hyu',thai:'เฮียว',type:'combo',mnemonic:'ひ + ゅ = ひゅ "เฮียว" เสียงผสม 🌬️',example:'ひゅーひゅー (hyuuhyuu) = เสียงลม'},
  {char:'ひょ',romaji:'hyo',thai:'เฮียว',type:'combo',mnemonic:'ひ + ょ = ひょ "เฮียว" เสียงผสม 🐾',example:'ひょう (hyou) = เสือดาว'},
  {char:'みゃ',romaji:'mya',thai:'เมียะ',type:'combo',mnemonic:'み + ゃ = みゃ "เมียะ" เสียงผสม 🎶',example:'みゃくはく (myakuhaku) = ชีพจร'},
  {char:'みゅ',romaji:'myu',thai:'เมียว',type:'combo',mnemonic:'み + ゅ = みゅ "เมียว" เสียงผสม 🎵',example:'みゅーじっく (myuujikku) = ดนตรี'},
  {char:'みょ',romaji:'myo',thai:'เมียว',type:'combo',mnemonic:'み + ょ = みょ "เมียว" เสียงผสม 🌸',example:'みょうじ (myouji) = นามสกุล'},
  {char:'りゃ',romaji:'rya',thai:'เรียะ',type:'combo',mnemonic:'り + ゃ = りゃ "เรียะ" เสียงผสม 🌟',example:'りゃくご (ryakugo) = ตัวย่อ'},
  {char:'りゅ',romaji:'ryu',thai:'ริว',type:'combo',mnemonic:'り + ゅ = りゅ "ริว" เหมือนมังกร 🐉',example:'りゅう (ryuu) = มังกร'},
  {char:'りょ',romaji:'ryo',thai:'เรียว',type:'combo',mnemonic:'り + ょ = りょ "เรียว" เสียงผสม 🏨',example:'りょこう (ryokou) = การท่องเที่ยว'},
];

// =====================================================
// DATA: Complete Katakana Database
// =====================================================

const KATAKANA = [
  {char:'ア',romaji:'a',thai:'อา',type:'vowel',mnemonic:'ตัวア เหมือนตัว A ที่หมุนไป "อา" เหมือน A ยักษ์ 🔠',example:'アイス (aisu) = ไอศกรีม'},
  {char:'イ',romaji:'i',thai:'อิ',type:'vowel',mnemonic:'ตัวイ เหมือนเลข 1 ที่มีขีด "อิ" เส้นตรงๆ 1️⃣',example:'イタリア (itaria) = อิตาลี'},
  {char:'ウ',romaji:'u',thai:'อุ',type:'vowel',mnemonic:'ตัวウ เหมือนแว่นตาขนาดเล็ก "อุ" แว่นสองตา 👓',example:'ウール (uuru) = ขนสัตว์'},
  {char:'エ',romaji:'e',thai:'เอ',type:'vowel',mnemonic:'ตัวエ เหมือนตัว I ที่มีแขน "เอ" หุ่นยนต์ 🤖',example:'エアコン (eakon) = แอร์'},
  {char:'オ',romaji:'o',thai:'โอ',type:'vowel',mnemonic:'ตัวオ เหมือนตัว オ ที่มีขีดตัดกลาง "โอ" ขีดแบ่ง ✂️',example:'オレンジ (orenji) = ส้ม'},
  {char:'カ',romaji:'ka',thai:'คะ',type:'k',mnemonic:'ตัวカ เหมือนใบพัดลม "คะ" หมุนๆ 🌀',example:'カメラ (kamera) = กล้อง'},
  {char:'キ',romaji:'ki',thai:'คิ',type:'k',mnemonic:'ตัวキ เหมือนรถไฟ "คิ" รางรถไฟ 🚂',example:'キッチン (kicchin) = ครัว'},
  {char:'ク',romaji:'ku',thai:'คุ',type:'k',mnemonic:'ตัวク เหมือนปากนกกางปีก "คุ" นกบิน 🐦',example:'クラス (kurasu) = ชั้นเรียน'},
  {char:'ケ',romaji:'ke',thai:'เค',type:'k',mnemonic:'ตัวケ เหมือนไม้พาย "เค" พายเรือ 🚣',example:'ケーキ (keeki) = เค้ก'},
  {char:'コ',romaji:'ko',thai:'โค',type:'k',mnemonic:'ตัวコ เหมือนกรอบหน้าต่าง "โค" มองออกไป 🪟',example:'コーヒー (koohii) = กาแฟ'},
  {char:'サ',romaji:'sa',thai:'ซะ',type:'s',mnemonic:'ตัวサ เหมือนคนยกมือ "ซะ" เรียกรถแท็กซี่ 🚕',example:'サービス (saabisu) = บริการ'},
  {char:'シ',romaji:'shi',thai:'ชิ',type:'s',mnemonic:'ตัวシ เหมือนรอยยิ้ม "ชิ" :) ยิ้มสวย 😊',example:'シャツ (shatsu) = เสื้อ'},
  {char:'ス',romaji:'su',thai:'ซุ',type:'s',mnemonic:'ตัวス เหมือนรูปสวอร์ด "ซุ" ดาบมีด้ามจับ ⚔️',example:'スーパー (suupaa) = ซุปเปอร์มาร์เก็ต'},
  {char:'セ',romaji:'se',thai:'เซ',type:'s',mnemonic:'ตัวセ เหมือนนาฬิกาที่ขาดเข็ม "เซ" เวลาหยุด ⏰',example:'セール (seeru) = เซล/ลดราคา'},
  {char:'ソ',romaji:'so',thai:'โซ',type:'s',mnemonic:'ตัวソ เหมือนคนยิ้มสั้นๆ "โซ" รอยยิ้มเล็กๆ 😁',example:'ソファ (sofa) = โซฟา'},
  {char:'タ',romaji:'ta',thai:'ตะ',type:'t',mnemonic:'ตัวタ เหมือนนกที่กางปีก "ตะ" นกบิน 🦅',example:'タクシー (takushii) = แท็กซี่'},
  {char:'チ',romaji:'chi',thai:'ชิ',type:'t',mnemonic:'ตัวチ เหมือนกุ้งมังกร "ชิ" ก้ามแข็ง 🦞',example:'チョコ (choko) = ช็อกโกแลต'},
  {char:'ツ',romaji:'tsu',thai:'ซึ',type:'t',mnemonic:'ตัวツ เหมือนรอยยิ้มที่กว้างกว่า "ซึ" ยิ้มกว้าง 😀',example:'ツアー (tsuaa) = ทัวร์'},
  {char:'テ',romaji:'te',thai:'เต',type:'t',mnemonic:'ตัวテ เหมือนเสาอากาศ TV "เต" รับสัญญาณ 📡',example:'テレビ (terebi) = โทรทัศน์'},
  {char:'ト',romaji:'to',thai:'โต',type:'t',mnemonic:'ตัวト เหมือนเสาที่มีหมุด "โต" ตอกหมุด 🔩',example:'トイレ (toire) = ห้องน้ำ'},
  {char:'ナ',romaji:'na',thai:'นะ',type:'n',mnemonic:'ตัวナ เหมือนตัวเลข 7 ที่มีขาค้ำ "นะ" เลข 7 ค้ำ 7️⃣',example:'ナイフ (naifu) = มีด'},
  {char:'ニ',romaji:'ni',thai:'นิ',type:'n',mnemonic:'ตัวニ เหมือนเลข 11 "นิ" เส้นสองอัน 11️⃣',example:'ニュース (nyuusu) = ข่าว'},
  {char:'ヌ',romaji:'nu',thai:'นุ',type:'n',mnemonic:'ตัวヌ เหมือนหนวดปู "นุ" ปูทะเล 🦀',example:'ヌードル (nuudoru) = บะหมี่'},
  {char:'ネ',romaji:'ne',thai:'เน',type:'n',mnemonic:'ตัวネ เหมือนตาข่าย "เน็ต" ตาข่ายจับสัตว์ 🕸️',example:'ネコ (neko) = แมว'},
  {char:'ノ',romaji:'no',thai:'โน',type:'n',mnemonic:'ตัวノ เหมือนเส้นเฉียง "โน" ขีดเส้น ✏️',example:'ノート (nooto) = สมุดโน้ต'},
  {char:'ハ',romaji:'ha',thai:'ฮะ',type:'h',mnemonic:'ตัวハ เหมือนขา "ฮะ" ขาเดินสองข้าง 🦿',example:'ハンバーガー (hanbaagaa) = แฮมเบอร์เกอร์'},
  {char:'ヒ',romaji:'hi',thai:'ฮิ',type:'h',mnemonic:'ตัวヒ เหมือนตัว F ที่ขาดขา "ฮิ" ตัว F ที่ถูกตัด ✂️',example:'ヒーロー (hiiroo) = ฮีโร่'},
  {char:'フ',romaji:'fu',thai:'ฟุ',type:'h',mnemonic:'ตัวフ เหมือนขอเบ็ด "ฟุ" ตกปลา 🎣',example:'フルーツ (furuutsu) = ผลไม้'},
  {char:'ヘ',romaji:'he',thai:'เฮ',type:'h',mnemonic:'ตัวヘ เหมือนภูเขา "เฮ" ปีนขึ้นเขา ⛰️',example:'ヘルメット (herumetto) = หมวกกันน็อก'},
  {char:'ホ',romaji:'ho',thai:'โฮ',type:'h',mnemonic:'ตัวホ เหมือนไม้กางเขน "โฮ" เสาสี่ขา ✝️',example:'ホテル (hoteru) = โรงแรม'},
  {char:'マ',romaji:'ma',thai:'มะ',type:'m',mnemonic:'ตัวマ เหมือนม้าที่กางหน้า "มะ" ม้าน่ารัก 🐴',example:'マクドナルド (makudonarudo) = แมคโดนัลด์'},
  {char:'ミ',romaji:'mi',thai:'มิ',type:'m',mnemonic:'ตัวミ เหมือนขีดสามขีด "มิ" เส้นสาม 🎵',example:'ミルク (miruku) = นม'},
  {char:'ム',romaji:'mu',thai:'มุ',type:'m',mnemonic:'ตัวム เหมือนรูปหน้าวัว "มุ" วัวมองหน้า 🐮',example:'ムービー (muubii) = หนัง'},
  {char:'メ',romaji:'me',thai:'เม',type:'m',mnemonic:'ตัวメ เหมือน X ขนาดใหญ่ "เม" ผิดข้ามออก ❌',example:'メニュー (menyuu) = เมนู'},
  {char:'モ',romaji:'mo',thai:'โม',type:'m',mnemonic:'ตัวモ เหมือนตะขอสองอัน "โม" ตะขอคู่ 🪝🪝',example:'モデル (moderu) = นางแบบ'},
  {char:'ヤ',romaji:'ya',thai:'ยะ',type:'y',mnemonic:'ตัวヤ เหมือนสถานีรถไฟ "ยะ" รถออก 🚂',example:'ヤクルト (yakuruto) = ยาคูลท์'},
  {char:'ユ',romaji:'yu',thai:'ยุ',type:'y',mnemonic:'ตัวユ เหมือนกีต้าร์ "ยุ" ดีดกีต้าร์ 🎸',example:'ユーチューブ (yuuchuubu) = YouTube'},
  {char:'ヨ',romaji:'yo',thai:'โย',type:'y',mnemonic:'ตัวヨ เหมือนตู้ "โย" ตู้สามชั้น 🗄️',example:'ヨーグルト (yooguruto) = โยเกิร์ต'},
  {char:'ラ',romaji:'ra',thai:'ระ',type:'r',mnemonic:'ตัวラ เหมือนไม้ขีดไฟ "ระ" ไฟลุก 🔥',example:'ラーメン (raamen) = ราเมน'},
  {char:'リ',romaji:'ri',thai:'ริ',type:'r',mnemonic:'ตัวリ เหมือนเสาสองต้น "ริ" ยืนตรง 🏛️',example:'リモコン (rimokon) = รีโมต'},
  {char:'ル',romaji:'ru',thai:'รุ',type:'r',mnemonic:'ตัวル เหมือนรองเท้าสองข้าง "รุ" เดินเดินๆ 👟',example:'ルール (ruuru) = กฎ'},
  {char:'レ',romaji:'re',thai:'เร',type:'r',mnemonic:'ตัวレ เหมือนขาคนที่เดิน "เร" ก้าวๆ 🦵',example:'レストラン (resutoran) = ร้านอาหาร'},
  {char:'ロ',romaji:'ro',thai:'โร',type:'r',mnemonic:'ตัวロ เหมือนหน้าต่างสี่เหลี่ยม "โร" กรอบสี่เหลี่ยม 🪟',example:'ロボット (robotto) = หุ่นยนต์'},
  {char:'ワ',romaji:'wa',thai:'วะ',type:'w',mnemonic:'ตัวワ เหมือนคน chill เอนตัว "วะ" ผ่อนคลาย 😎',example:'ワイン (wain) = ไวน์'},
  {char:'ヲ',romaji:'wo',thai:'โว',type:'w',mnemonic:'ตัวヲ "โว" ใช้เป็น particle ในภาษาทางการ 📜',example:'ほんヲ (hon wo) = หนังสือ'},
  {char:'ン',romaji:'n',thai:'น',type:'special',mnemonic:'ตัวン เหมือนตัว ソ ที่คล้ายกัน แต่เอียงกว่า "น" ระวังสับสนกับ ソ! 😅',example:'アイスクリーン (aisukuriin) = ไอศกรีม'},
  // Dakuten
  {char:'ガ',romaji:'ga',thai:'กะ',type:'dakuten',mnemonic:'カ + dakuten = ガ "กะ" เสียงก้อง 🎮',example:'ガム (gamu) = หมากฝรั่ง'},
  {char:'ギ',romaji:'gi',thai:'กิ',type:'dakuten',mnemonic:'キ + dakuten = ギ "กิ" เสียงก้อง 🎸',example:'ギター (gitaa) = กีตาร์'},
  {char:'グ',romaji:'gu',thai:'กุ',type:'dakuten',mnemonic:'ク + dakuten = グ "กุ" เสียงก้อง 🍇',example:'グラス (gurasu) = แก้วน้ำ'},
  {char:'ゲ',romaji:'ge',thai:'เก',type:'dakuten',mnemonic:'ケ + dakuten = ゲ "เก" เสียงก้อง 🎮',example:'ゲーム (geemu) = เกม'},
  {char:'ゴ',romaji:'go',thai:'โก',type:'dakuten',mnemonic:'コ + dakuten = ゴ "โก" เสียงก้อง ⛳',example:'ゴルフ (gorufu) = กอล์ฟ'},
  {char:'ザ',romaji:'za',thai:'ซะ',type:'dakuten',mnemonic:'サ + dakuten = ザ "ซะ" เสียงก้อง 🌸',example:'ザ・ベスト (za besuto) = The Best'},
  {char:'ジ',romaji:'ji',thai:'จิ',type:'dakuten',mnemonic:'シ + dakuten = ジ "จิ" เสียงก้อง 🎯',example:'ジュース (juusu) = น้ำผลไม้'},
  {char:'ズ',romaji:'zu',thai:'ซุ',type:'dakuten',mnemonic:'ス + dakuten = ズ "ซุ" เสียงก้อง 🔊',example:'ズボン (zubon) = กางเกง'},
  {char:'ゼ',romaji:'ze',thai:'เซ',type:'dakuten',mnemonic:'セ + dakuten = ゼ "เซ" เสียงก้อง 0️⃣',example:'ゼロ (zero) = ศูนย์'},
  {char:'ゾ',romaji:'zo',thai:'โซ',type:'dakuten',mnemonic:'ソ + dakuten = ゾ "โซ" เสียงก้อง 🧟',example:'ゾンビ (zonbi) = ซอมบี้'},
  {char:'ダ',romaji:'da',thai:'ดะ',type:'dakuten',mnemonic:'タ + dakuten = ダ "ดะ" เสียงก้อง 💃',example:'ダンス (dansu) = เต้นรำ'},
  {char:'ヂ',romaji:'di',thai:'ดิ',type:'dakuten',mnemonic:'チ + dakuten = ヂ "ดิ" เสียงก้อง (ใช้น้อย) 📝',example:''},
  {char:'ヅ',romaji:'du',thai:'ดุ',type:'dakuten',mnemonic:'ツ + dakuten = ヅ "ดุ" เสียงก้อง (ใช้น้อย) 📝',example:''},
  {char:'デ',romaji:'de',thai:'เด',type:'dakuten',mnemonic:'テ + dakuten = デ "เด" เสียงก้อง 🖥️',example:'デパート (depaato) = ห้างสรรพสินค้า'},
  {char:'ド',romaji:'do',thai:'โด',type:'dakuten',mnemonic:'ト + dakuten = ド "โด" เสียงก้อง 🚪',example:'ドア (doa) = ประตู'},
  {char:'バ',romaji:'ba',thai:'บะ',type:'dakuten',mnemonic:'ハ + dakuten = バ "บะ" เสียงก้อง 🚌',example:'バス (basu) = รถบัส'},
  {char:'ビ',romaji:'bi',thai:'บิ',type:'dakuten',mnemonic:'ヒ + dakuten = ビ "บิ" เสียงก้อง 🍺',example:'ビール (biiru) = เบียร์'},
  {char:'ブ',romaji:'bu',thai:'บุ',type:'dakuten',mnemonic:'フ + dakuten = ブ "บุ" เสียงก้อง 🔵',example:'ブルー (buruu) = สีน้ำเงิน'},
  {char:'ベ',romaji:'be',thai:'เบ',type:'dakuten',mnemonic:'ヘ + dakuten = ベ "เบ" เสียงก้อง 🛏️',example:'ベッド (beddo) = เตียง'},
  {char:'ボ',romaji:'bo',thai:'โบ',type:'dakuten',mnemonic:'ホ + dakuten = ボ "โบ" เสียงก้อง ⚽',example:'ボール (booru) = ลูกบอล'},
  {char:'パ',romaji:'pa',thai:'ปะ',type:'dakuten',mnemonic:'ハ + handakuten = パ "ปะ" เสียงชัดเจน 🎉',example:'パーティー (paatii) = ปาร์ตี้'},
  {char:'ピ',romaji:'pi',thai:'ปิ',type:'dakuten',mnemonic:'ヒ + handakuten = ピ "ปิ" เสียงชัดเจน 🍕',example:'ピザ (piza) = พิซซ่า'},
  {char:'プ',romaji:'pu',thai:'ปุ',type:'dakuten',mnemonic:'フ + handakuten = プ "ปุ" เสียงชัดเจน 🏊',example:'プール (puuru) = สระว่ายน้ำ'},
  {char:'ペ',romaji:'pe',thai:'เป',type:'dakuten',mnemonic:'ヘ + handakuten = ペ "เป" เสียงชัดเจน 🐧',example:'ペンギン (pengin) = เพนกวิน'},
  {char:'ポ',romaji:'po',thai:'โป',type:'dakuten',mnemonic:'ホ + handakuten = ポ "โป" เสียงชัดเจน 📮',example:'ポスト (posuto) = ตู้ไปรษณีย์'},
  // Combination sounds
  {char:'キャ',romaji:'kya',thai:'เคียะ',type:'combo',mnemonic:'キ + ャ = キャ "เคียะ" เสียงผสม 🎠',example:'キャンパス (kyanpasu) = แคมปัส'},
  {char:'キュ',romaji:'kyu',thai:'เคียว',type:'combo',mnemonic:'キ + ュ = キュ "เคียว" เสียงผสม 🐰',example:'キュート (kyuuto) = น่ารัก'},
  {char:'キョ',romaji:'kyo',thai:'เคียว',type:'combo',mnemonic:'キ + ョ = キョ "เคียว" เสียงผสม 🎭',example:'キョウト (kyouto) = เกียวโต'},
  {char:'シャ',romaji:'sha',thai:'ชะ',type:'combo',mnemonic:'シ + ャ = シャ "ชะ" เสียงผสม 🚿',example:'シャワー (shawaa) = ฝักบัว'},
  {char:'シュ',romaji:'shu',thai:'ชุ',type:'combo',mnemonic:'シ + ュ = シュ "ชุ" เสียงผสม 🍰',example:'シュークリーム (shuukuriimu) = ชูครีม'},
  {char:'ショ',romaji:'sho',thai:'โชะ',type:'combo',mnemonic:'シ + ョ = ショ "โชะ" เสียงผสม 🛍️',example:'ショッピング (shoppingu) = ช้อปปิ้ง'},
  {char:'チャ',romaji:'cha',thai:'ชะ',type:'combo',mnemonic:'チ + ャ = チャ "ชะ" เสียงผสม 🍵',example:'チャンネル (channeru) = ช่องทีวี'},
  {char:'チュ',romaji:'chu',thai:'ชุ',type:'combo',mnemonic:'チ + ュ = チュ "ชุ" เสียงผสม 🖥️',example:'チューブ (chuubu) = ท่อ/ยูทูบ'},
  {char:'チョ',romaji:'cho',thai:'โชะ',type:'combo',mnemonic:'チ + ョ = チョ "โชะ" เสียงผสม 🍫',example:'チョコレート (chokoreeto) = ช็อกโกแลต'},
  {char:'ニャ',romaji:'nya',thai:'เนียะ',type:'combo',mnemonic:'ニ + ャ = ニャ "เนียะ" เสียงแมว 🐱',example:'ニャン (nyan) = เสียงแมว'},
  {char:'ニュ',romaji:'nyu',thai:'เนียว',type:'combo',mnemonic:'ニ + ュ = ニュ "เนียว" เสียงผสม 📰',example:'ニュース (nyuusu) = ข่าว'},
  {char:'ニョ',romaji:'nyo',thai:'เนียว',type:'combo',mnemonic:'ニ + ョ = ニョ "เนียว" เสียงผสม 🌿',example:'ニョロ (nyoro) = เลื้อยๆ'},
  {char:'ヒャ',romaji:'hya',thai:'เฮียะ',type:'combo',mnemonic:'ヒ + ャ = ヒャ "เฮียะ" เสียงผสม 💫',example:'ヒャク (hyaku) = หนึ่งร้อย'},
  {char:'ヒュ',romaji:'hyu',thai:'เฮียว',type:'combo',mnemonic:'ヒ + ュ = ヒュ "เฮียว" เสียงผสม 🌬️',example:'ヒューズ (hyuuzu) = ฟิวส์'},
  {char:'ヒョ',romaji:'hyo',thai:'เฮียว',type:'combo',mnemonic:'ヒ + ョ = ヒョ "เฮียว" เสียงผสม 🐆',example:'ヒョウ (hyou) = เสือดาว'},
  {char:'ミャ',romaji:'mya',thai:'เมียะ',type:'combo',mnemonic:'ミ + ャ = ミャ "เมียะ" เสียงผสม 🌺',example:'ミャンマー (myanmaa) = เมียนมา'},
  {char:'ミュ',romaji:'myu',thai:'เมียว',type:'combo',mnemonic:'ミ + ュ = ミュ "เมียว" เสียงผสม 🎵',example:'ミュージック (myuujikku) = ดนตรี'},
  {char:'ミョ',romaji:'myo',thai:'เมียว',type:'combo',mnemonic:'ミ + ョ = ミョ "เมียว" เสียงผสม 🌸',example:'ミョウガ (myouga) = ขิงฤดู'},
  {char:'リャ',romaji:'rya',thai:'เรียะ',type:'combo',mnemonic:'リ + ャ = リャ "เรียะ" เสียงผสม ⭐',example:'リャクゴ (ryakugo) = ตัวย่อ'},
  {char:'リュ',romaji:'ryu',thai:'ริว',type:'combo',mnemonic:'リ + ュ = リュ "ริว" มังกรบิน 🐉',example:'リュック (ryukku) = เป้สะพาย'},
  {char:'リョ',romaji:'ryo',thai:'เรียว',type:'combo',mnemonic:'リ + ョ = リョ "เรียว" เสียงผสม 🏨',example:'リョコウ (ryokou) = ท่องเที่ยว'},
];

// =====================================================
// STATE MANAGEMENT
// =====================================================

const ACHIEVEMENTS = [
  {id:'first_kana',icon:'🎌',name:'ตัวแรก',desc:'เรียนตัวอักษรแรก'},
  {id:'ten_kana',icon:'🔟',name:'10 ตัว',desc:'จำตัวอักษรได้ 10 ตัว'},
  {id:'all_hira',icon:'あ',name:'ฮิรางานะ',desc:'จำฮิรางานะครบ'},
  {id:'all_kata',icon:'ア',name:'คาตาคานะ',desc:'จำคาตาคานะครบ'},
  {id:'quiz_100',icon:'⭐',name:'100 แต้ม',desc:'ทำ Quiz ได้ 100 แต้ม'},
  {id:'level5',icon:'🏆',name:'Level 5',desc:'ขึ้นถึง Level 5'},
  {id:'streak7',icon:'🔥',name:'7 วัน',desc:'เรียนต่อเนื่อง 7 วัน'},
  {id:'memory_pro',icon:'🧠',name:'Memory Pro',desc:'ชนะ Memory Game'},
  {id:'first_quiz',icon:'⚔️',name:'นักสู้',desc:'เล่น Quiz ครั้งแรก'},
  {id:'total_100',icon:'💯',name:'100 XP',desc:'สะสม XP ได้ 100'},
  {id:'writer',icon:'✍️',name:'นักเขียน',desc:'ฝึกเขียน 10 ครั้ง'},
  {id:'speaker',icon:'🔊',name:'นักพูด',desc:'ฟังเสียง 20 ครั้ง'},
  {id:'combo5',icon:'🌟',name:'Combo x5',desc:'ตอบถูกต่อกัน 5 ครั้ง'},
  {id:'all_done',icon:'👑',name:'ปรมาจารย์',desc:'จำได้ทุกตัวอักษร'},
  {id:'level10',icon:'🏅',name:'Level 10',desc:'ขึ้นถึง Level 10'},
];


const MISSIONS = [
  {id:'learn5',text:'เรียนตัวอักษรใหม่ 5 ตัว',xp:20},
  {id:'quiz1',text:'ทำ Quiz 1 ครั้ง',xp:15},
  {id:'flashcard10',text:'ดู Flashcard 10 ใบ',xp:10},
  {id:'streak',text:'รักษา Streak ต่อเนื่อง',xp:25},
  {id:'write5',text:'ฝึกเขียน 5 ตัว',xp:15},
];

const TIPS = [
  'เริ่มต้นจากสระก่อนนะคะ あ い う え お เพราะจะเป็นพื้นฐานของทุกแถว! 🌟',
  'ฝึกเขียนทุกวัน แม้แค่ 5 นาทีก็ช่วยได้มากค่ะ! ✍️',
  'ลองสร้างประโยคเชื่อมโยงกับชีวิตประจำวัน เช่น ねこ = แมว นึกถึงแมวตัวโปรดเลยค่ะ! 🐱',
  'คาตาคานะใช้กับคำทับศัพท์ เช่น コーヒー (coffee) ลองอ่านป้ายร้านค้าญี่ปุ่นดูนะคะ ☕',
  'Spaced Repetition คือเคล็ดลับ! ฝึกตัวที่ยากบ่อยๆ จะจำได้เร็วขึ้นค่ะ 🧠',
  'ฟังเสียงควบคู่ไปกับการอ่านเสมอ ช่วยให้จำได้ทั้งรูปและเสียงค่ะ! 🔊',
  'อย่าท้อนะคะ! ทุกคนเรียนรู้ในอัตราที่ต่างกัน ค่อยๆ ไปก็ได้ค่ะ 💪',
  'ลองหาเพื่อนเรียนด้วยกัน จะสนุกและช่วยกระตุ้นได้มากขึ้นค่ะ! 👫',
];

// =====================================================
// JP BG TEXT
// =====================================================


// ===== SONG ENGINE — Single Timeline =====

const CHARACTERS = [
  { id:'haruna',  name:'ฮารุนะ',          nameJP:'はるな',        emoji:'🌸', age:22, job:'นักศึกษา',         jobJP:'だいがくせい',    color:'#ff6b9d', bg:'linear-gradient(135deg,#ff6b9d,#b39ddb)', tag:'น่ารัก/ช่างพูด',      personality:'พูดเยอะ ใจดี ชอบใช้คำลงท้าย ね และ よ',                    origin:'โตเกียว',   hobby:'วาดภาพและดูอนิเมะ',        style:'friendly', tips:'ฮารุนะพูดเร็วและใช้ภาษาสแลงญี่ปุ่นบ้างค่ะ!' },
  { id:'kenji',   name:'เคนจิ',           nameJP:'けんじ',        emoji:'😎', age:28, job:'โปรแกรมเมอร์',    jobJP:'プログラマー',   color:'#4fc3f7', bg:'linear-gradient(135deg,#4fc3f7,#1976d2)', tag:'เท่/พูดน้อย',         personality:'พูดสั้น กระชับ ตรงประเด็น ไม่ค่อยแสดงความรู้สึก',         origin:'โอซาก้า',   hobby:'เล่นเกมและดูหนัง',        style:'cool',     tips:'เคนจิพูดสั้นๆ แต่ตรงประเด็นมากค่ะ!' },
  { id:'yuki',    name:'ยูกิ',            nameJP:'ゆき',          emoji:'❄️', age:19, job:'นักเรียนมัธยม',   jobJP:'こうこうせい',   color:'#80deea', bg:'linear-gradient(135deg,#80deea,#4fc3f7)', tag:'ขี้อาย/สุภาพ',        personality:'พูดเบาๆ ขี้อาย มักใช้คำ すみません และ あの...',             origin:'ฮอกไกโด',  hobby:'อ่านหนังสือและฟังเพลง',   style:'shy',      tips:'ยูกิขี้อายมาก อาจตอบช้าหน่อยนะคะ!' },
  { id:'tanaka',  name:'ทานากะซัง',       nameJP:'たなかさん',    emoji:'👔', age:45, job:'ผู้จัดการบริษัท', jobJP:'かいしゃいん',   color:'#78909c', bg:'linear-gradient(135deg,#78909c,#455a64)', tag:'ทางการ/มืออาชีพ',     personality:'พูดสุภาพมาก ใช้ภาษาทางการ คำลงท้าย ます/です เสมอ',        origin:'นาโกย่า',  hobby:'กอล์ฟและดื่มชา',          style:'formal',   tips:'ทานากะซังพูดสุภาพมาก ดีสำหรับฝึกภาษาทางการค่ะ!' },
  { id:'hana',    name:'ฮานะจัง',         nameJP:'はなちゃん',    emoji:'🌺', age:16, job:'นักเรียน',         jobJP:'がくせい',       color:'#f48fb1', bg:'linear-gradient(135deg,#f48fb1,#ff6b9d)', tag:'สดใส/พลังงานสูง',     personality:'ร่าเริงมาก พูดเร็ว ใช้ แล้วก็ และ ใช่มั้ย บ่อย',           origin:'เกียวโต',  hobby:'เต้น K-pop และกิน',        style:'energetic',tips:'ฮานะจังพูดเร็วมาก ลองฟังให้ทันนะคะ!' },
  { id:'ojisan',  name:'โอจิซัง',         nameJP:'おじさん',      emoji:'👴', age:65, job:'เกษียณแล้ว',      jobJP:'たいしょくした', color:'#a5d6a7', bg:'linear-gradient(135deg,#a5d6a7,#66bb6a)', tag:'ผู้เฒ่า/ใจดี',        personality:'พูดช้าๆ ใจดีมาก ชอบเล่าเรื่องสมัยก่อน ใช้คำโบราณ',        origin:'เกียวโต',  hobby:'ทำสวนและตกปลา',           style:'old',      tips:'โอจิซังพูดช้าๆ ชัดเจน เหมาะกับผู้เริ่มต้นค่ะ!' },
  { id:'ryu',     name:'ริวจัง',          nameJP:'りゅうちゃん',  emoji:'🐉', age:14, job:'นักเรียนมัธยมต้น',jobJP:'ちゅうがくせい', color:'#ce93d8', bg:'linear-gradient(135deg,#ce93d8,#9c27b0)', tag:'เด็ก/ซน',             personality:'พูดเร็ว ซน ใช้สแลงเยาวชน やばい และ マジ บ่อย',            origin:'โตเกียว',  hobby:'ฟุตบอลและมังกะ',          style:'young',    tips:'ริวจังใช้ภาษาวัยรุ่นญี่ปุ่น ท้าทายมากค่ะ!' },
  { id:'sakura',  name:'ซากุระ',          nameJP:'さくら',        emoji:'🌸', age:30, job:'ครูประถม',         jobJP:'せんせい',       color:'#ffab91', bg:'linear-gradient(135deg,#ffab91,#ff7043)', tag:'อบอุ่น/ใจเย็น',       personality:'พูดชัด ช้า อธิบายละเอียด อดทน ใจดีมาก',                   origin:'ฟุกุโอกะ', hobby:'ทำอาหารและถ่ายรูป',       style:'friendly', tips:'ซากุระพูดชัดเจนมาก เหมาะกับฝึกฟังค่ะ!' },
  { id:'boss',    name:'บอสซัง',          nameJP:'ぼすさん',      emoji:'💼', age:38, job:'เจ้าของร้านอาหาร', jobJP:'オーナー',       color:'#ffcc02', bg:'linear-gradient(135deg,#ffcc02,#ff9800)', tag:'จริงจัง/ตรงไปตรงมา',  personality:'ตรงไปตรงมา บางครั้งขึงขัง แต่ใจดีถ้ารู้จัก',              origin:'โอซาก้า',  hobby:'ทำอาหารและดูกีฬา',        style:'blunt',    tips:'บอสซังพูดตรงๆ อาจดูขึงขังนิดนึงนะคะ!' },
  { id:'miku',    name:'มิกุจัง',         nameJP:'みくちゃん',    emoji:'🎵', age:20, job:'นักร้อง/สตรีมเมอร์',jobJP:'かしゅ',        color:'#b39ddb', bg:'linear-gradient(135deg,#b39ddb,#7c4dff)', tag:'ชอบสังคม/ร่าเริง',    personality:'ร่าเริงสดใส ชอบเปรียบเทียบกับเพลง ใช้ คาวาอี้ บ่อย',      origin:'ซัปโปโร', hobby:'ร้องเพลงและเล่นเกม',       style:'energetic',tips:'มิกุจังร่าเริงมาก บทสนทนาสนุกแน่นอนค่ะ!' },
  { id:'taro',    name:'ทาโร่',           nameJP:'たろう',        emoji:'🤓', age:25, job:'นักวิจัย',         jobJP:'けんきゅうしゃ', color:'#80cbc4', bg:'linear-gradient(135deg,#80cbc4,#009688)', tag:'ฉลาด/ช่างคิด',        personality:'คิดเยอะ พูดวิเคราะห์ ชอบอธิบายเหตุผล ใช้คำยากบ้าง',       origin:'โตเกียว',  hobby:'อ่านหนังสือวิทยาศาสตร์', style:'formal',   tips:'ทาโร่ใช้คำศัพท์ยากนิดนึง แต่อธิบายดีมากค่ะ!' },
  { id:'mama',    name:'คาคาซัง',         nameJP:'おかあさん',    emoji:'👩‍🍳',age:48, job:'แม่บ้าน',          jobJP:'しゅふ',         color:'#ef9a9a', bg:'linear-gradient(135deg,#ef9a9a,#e53935)', tag:'เมตตา/ห่วงใย',        personality:'อบอุ่นมาก ห่วงใย ชอบเสนอให้กิน ใช้ ねえ บ่อย',             origin:'นาโกย่า',  hobby:'ทำอาหารและดูซีรีส์',     style:'friendly', tips:'คาคาซังอบอุ่นมาก รู้สึกเหมือนคุยกับแม่ค่ะ!' },
  { id:'gamer',   name:'โนบุจัง',         nameJP:'のぶちゃん',    emoji:'🎮', age:17, job:'นักเรียน(เกมเมอร์)',jobJP:'ゲーマー',       color:'#69f0ae', bg:'linear-gradient(135deg,#69f0ae,#00bcd4)', tag:'เกมเมอร์/สแลงเยอะ',   personality:'ใช้ศัพท์เกมบ่อย やられた GG ชอบเปรียบกับเกม',              origin:'โตเกียว',  hobby:'เล่นเกมออนไลน์ตลอด',     style:'young',    tips:'โนบุจังใช้ศัพท์เกมและสแลงสมัยใหม่เยอะมากค่ะ!' },
  { id:'tourist', name:'อากิระซัง',       nameJP:'あきらさん',    emoji:'✈️', age:32, job:'นักท่องเที่ยว',    jobJP:'りょこうしゃ',   color:'#ffd740', bg:'linear-gradient(135deg,#ffd740,#ff9800)', tag:'นักท่องเที่ยว/อยากรู้',personality:'กระตือรือร้น ถามเยอะ อยากรู้เรื่องไทย ตื่นเต้นกับทุกอย่าง',origin:'ฮิโรชิมา', hobby:'ท่องเที่ยวและถ่ายรูป',    style:'energetic',tips:'อากิระซังอยากรู้เรื่องไทยมาก ลองอธิบายดูนะคะ!' },
  { id:'chef',    name:'ชีฟ ยามาดะ',      nameJP:'シェフやまだ',  emoji:'👨‍🍳',age:40, job:'เชฟ',              jobJP:'りょうりにん',   color:'#ff7043', bg:'linear-gradient(135deg,#ff7043,#e64a19)', tag:'หัวร้อน/ใจดีซ่อนเร้น',personality:'พูดตรงๆ บางทีดุ แต่จริงๆ ใจดีมาก ชอบพูดเรื่องอาหาร',      origin:'โอซาก้า',  hobby:'คิดค้นเมนูใหม่',          style:'blunt',    tips:'ชีฟยามาดะดูดุแต่ใจดีมากค่ะ อดทนหน่อยนะ!' },
  { id:'idol',    name:'ฮิมาริจัง',       nameJP:'ひまりちゃん',  emoji:'⭐', age:18, job:'ไอดอล(ฝึกหัด)',    jobJP:'アイドル',       color:'#f8bbd0', bg:'linear-gradient(135deg,#f8bbd0,#e91e63)', tag:'ไอดอล/สุภาพมาก',      personality:'สุภาพมากๆ ยิ้มตลอด พูดหวานๆ ใช้ ありがとうございます บ่อย', origin:'โตเกียว',  hobby:'ฝึกร้องเพลงและเต้น',     style:'friendly', tips:'ฮิมาริจังสุภาพมากที่สุดในบรรดาตัวละครทั้งหมดค่ะ!' },
  { id:'salaryman',name:'ซาโต้ซัง',       nameJP:'さとうさん',    emoji:'🏃', age:35, job:'พนักงานออฟฟิศ',   jobJP:'サラリーマン',   color:'#90a4ae', bg:'linear-gradient(135deg,#90a4ae,#607d8b)', tag:'รีบร้อน/เครียด',      personality:'รีบตลอด เครียด พูดสั้น ใช้ ちょっと待って บ่อย',            origin:'โตเกียว',  hobby:'ดื่มเบียร์กับเพื่อน',    style:'cool',     tips:'ซาโต้ซังรีบตลอด บางทีตัดบทสั้นๆ ค่ะ!' },
  { id:'grandma', name:'โอบาจัง',         nameJP:'おばあちゃん',  emoji:'👵', age:72, job:'เกษียณแล้ว',      jobJP:'たいしょくした', color:'#bcaaa4', bg:'linear-gradient(135deg,#bcaaa4,#8d6e63)', tag:'คุณยาย/ใจดีมาก',      personality:'ใจดีมาก พูดช้า ชอบเล่าเรื่องสมัยก่อน ให้กำลังใจเสมอ',     origin:'เกียวโต',  hobby:'ทำขนมและชมสวน',          style:'old',      tips:'โอบาจังพูดช้าและชัดมาก เหมาะสำหรับผู้เริ่มต้นค่ะ!' },
  { id:'foreign', name:'เคน (ฝรั่งเรียนญี่ปุ่น)',nameJP:'けん', emoji:'🌍', age:24, job:'นักศึกษาแลกเปลี่ยน',jobJP:'りゅうがくせい', color:'#a5d6a7', bg:'linear-gradient(135deg,#a5d6a7,#4caf50)', tag:'ฝรั่ง/ญี่ปุ่นงูๆปลาๆ',personality:'ภาษาญี่ปุ่นไม่เก่งมาก บางทีพูดผิด แต่พยายามมาก',           origin:'อเมริกา',  hobby:'เรียนภาษาและท่องเที่ยว',style:'friendly', tips:'เคนภาษาญี่ปุ่นยังไม่เก่ง ลองช่วยสอนเขาดูนะคะ!' },
  { id:'nurse',   name:'มิโฮะซัง',        nameJP:'みほさん',      emoji:'👩‍⚕️',age:27, job:'พยาบาล',          jobJP:'かんごし',       color:'#80cbc4', bg:'linear-gradient(135deg,#80cbc4,#26a69a)', tag:'ใส่ใจ/ละเอียด',        personality:'พูดอย่างระมัดระวัง ชัดเจน ห่วงใย ถามสุขภาพบ่อย',           origin:'ฟุกุโอกะ', hobby:'โยคะและทำสวน',            style:'friendly', tips:'มิโฮะซังพูดชัดและห่วงใยมากค่ะ!' },
  { id:'monk',    name:'โอโชซัง',         nameJP:'おしょうさん',  emoji:'🙏', age:55, job:'พระ',              jobJP:'おぼうさん',     color:'#ffd740', bg:'linear-gradient(135deg,#ffd740,#ff9800)', tag:'สงบ/ปราชญ์',          personality:'พูดช้าๆ ใช้ภาษาเชิงปรัชญา มักอ้างคำสอน สงบเย็น',          origin:'เกียวโต',  hobby:'นั่งสมาธิและทำสวนหิน',   style:'old',      tips:'โอโชซังพูดลึกและสงบ เหมาะฝึกภาษาระดับสูงค่ะ!' },
];

// ===== SCENE DATA =====
// responses แยกตาม style: friendly / formal / shy / energetic / cool / old / young / blunt
const SCENES = {
  greeting: {
    name:'👋 ทักทาย',
    opener: {
      friendly: ['こんにちは！😊 ดีใจที่ได้เจอนะคะ！','สวัสดีค่ะ！こんにちは！มาจากไหนเหรอคะ？'],
      formal:   ['こんにちは。よろしくお願いします。','お会いできて光栄です。ขอแนะนำตัวด้วยนะครับ'],
      shy:      ['あ...こんにちは... 😳 ขอโทษที่พูดเบาไปนะคะ...','こ、こんにちは... ยินดีที่ได้รู้จักค่ะ (ก้มหัว)'],
      energetic:['こんにちは！！🎉 ยินดีมากกกเลยย！！เจอคนใหม่แล้วตื่นเต้นมาก！','わあ！こんにちは！！สวัสดีๆๆ！ดีใจจังเลย！'],
      cool:     ['こんにちは。','ยินดี。'],
      old:      ['おお、こんにちは。ยินดีที่ได้รู้จักนะ เด็กๆ สมัยนี้น่ารักจัง','こんにちは。ลองนั่งคุยกันดีกว่านะ'],
      young:    ['うっす！こんにちは！やばくない？新しい人だ！','こんにちは！マジで？はじめまして！'],
      blunt:    ['こんにちは。ตรงๆ เลยนะ ยินดีที่ได้รู้จัก','ああ、こんにちは。มีอะไรไหม?'],
    },
    choices: ['こんにちは！(สวัสดี)','おはようございます！(อรุณสวัสดิ์)','こんばんは！(ราตรีสวัสดิ์)','はじめまして！(ยินดีที่ได้รู้จัก)'],
    responses: {
      'こんにちは！(สวัสดี)': {
        friendly: ['こんにちは！🌸 ดีมากเลยค่ะ！ตอนนี้เป็นยังไงบ้าง？','こんにちは！พูดได้ดีมากนะคะ！'],
        formal:   ['こんにちは。お元気ですか？','こんにちは。どうぞよろしくお願いします。'],
        shy:      ['あ...こんにちは... (ยิ้มเบาๆ) ดีใจที่คุณทักทายค่ะ','こんにちは... 😊'],
        energetic:['こんにちは！！やったー！！🎉 สุดยอดมากก！','こんにちは！！ตื่นเต้นมากเลย！'],
        cool:     ['ああ、こんにちは。','うん。'],
        old:      ['こんにちは！อ้าว พูดญี่ปุ่นได้ด้วยนะ เก่งจังเลย！','こんにちは！ดีใจนะที่เห็นคนรุ่นใหม่เรียนภาษาญี่ปุ่น'],
        young:    ['こんにちは！マジか！上手じゃん！','うっす！やるじゃん！'],
        blunt:    ['こんにちは。พูดได้ดี','ああ。こんにちは。'],
      },
      'おはようございます！(อรุณสวัสดิ์)': {
        friendly: ['おはようございます！🌅 เช้านี้อากาศดีจังนะคะ！','おはよう！ตื่นเช้าจังเลยนะคะ！'],
        formal:   ['おはようございます。お早いですね。','おはようございます。今日もよろしくお願いします。'],
        shy:      ['お...おはようございます... ☀️','おはようございます... (ยิ้มขำขำ)'],
        energetic:['おはよーございます！！☀️☀️ วันนี้จะเป็นวันที่ดีแน่นอน！！','おはようございます！！ตื่นเช้าเหมือนกันเลย！！'],
        cool:     ['おはよう。','ああ、おはよう。'],
        old:      ['おはようございます！ดีนะ ตื่นเช้า ร่างกายแข็งแรง！','おはよう！เด็กรุ่นใหม่นี่ขยันดี'],
        young:    ['おはようございます！はや！まだ眠い...','おはよー！早起きだね！'],
        blunt:    ['おはよう。','ああ。'],
      },
      'こんばんは！(ราตรีสวัสดิ์)': {
        friendly: ['こんばんは！🌙 คืนนี้อากาศดีนะคะ！','こんばんは！ทำอะไรอยู่คืนนี้คะ？'],
        formal:   ['こんばんは。夜遅くにすみません。','こんばんは。お疲れ様です。'],
        shy:      ['こ...こんばんは... 🌙 คืนนี้เงียบดีนะคะ','こんばんは...'],
        energetic:['こんばんは！！🌟 คืนนี้สนุกมากเลย！！','こんばんは！คืนนี้ยังไม่ง่วงเลย！！'],
        cool:     ['こんばんは。','ああ。'],
        old:      ['こんばんは。คืนแล้วหรอ เวลาผ่านไปเร็วจัง','こんばんは。ระวังเรื่องสุขภาพด้วยนะ'],
        young:    ['こんばんは！夜更かし？','こんばんは！まだ起きてたの？'],
        blunt:    ['こんばんは。','ああ、こんばんは。'],
      },
      'はじめまして！(ยินดีที่ได้รู้จัก)': {
        friendly: ['はじめまして！🌸 ดีใจมากที่ได้รู้จักค่ะ！どうぞよろしく！','はじめまして！ญี่ปุ่นเรียนมานานไหมคะ？'],
        formal:   ['はじめまして。どうぞよろしくお願いいたします。','はじめまして。お名前を聞かせていただけますか？'],
        shy:      ['は...はじめまして... 😳 よろしくお願いします...','はじめまして... (โค้งศีรษะ) ยินดีค่ะ'],
        energetic:['はじめまして！！🎉 うわー！！新しい友達だ！！','はじめまして！！よろしくーー！！'],
        cool:     ['はじめまして。よろしく。','ああ、はじめまして。'],
        old:      ['はじめまして。ยินดีที่ได้รู้จักนะหนู','はじめまして。นั่งลงก่อนนะ อย่าเป็นทางการ'],
        young:    ['はじめまして！よろしく！フレンドになろう！','はじめましてー！よろしくー！'],
        blunt:    ['はじめまして。よろしく。','ああ。はじめまして。'],
      },
    },
    followups: {
      friendly: ['お名前は何ですか？ชื่ออะไรคะ？','どこから来ましたか？มาจากไหนคะ？🌏'],
      formal:   ['どちらからいらっしゃいましたか？','お仕事は何をされていますか？'],
      shy:      ['あの...お名前を聞いてもいいですか...？','よかったら...もう少し話しませんか...？'],
      energetic:['名前は何！？早く教えて！！','どこに住んでるの！？！？'],
      cool:     ['名前は？','どこから？'],
      old:      ['お名前は何というんですか？','どこからいらしたんですか？'],
      young:    ['名前何？LINEある？','どこ住み？'],
      blunt:    ['名前は？','どこから来た？'],
    }
  },

  intro: {
    name:'🙋 แนะนำตัว',
    opener: {
      friendly: ['さあ、自己紹介しましょうか！🌸 ฉันจะแนะนำตัวก่อนนะคะ！','มาแนะนำตัวกันเถอะค่ะ！私から始めますね！'],
      formal:   ['自己紹介をさせていただきます。ขอแนะนำตัวด้วยครับ','まず私の方から自己紹介いたします。'],
      shy:      ['あの...自己紹介...しますね... 😳','じ、自己紹介...できるか不安だけど...がんばります！'],
      energetic:['自己紹介タイム！！🎉 わくわく！！','さあ！自己紹介しよう！！楽しいよ！！'],
      cool:     ['自己紹介する。聞いて。','まあ、自己紹介くらいするか。'],
      old:      ['では自己紹介しましょうか。','みなさん、授業を始めますよ。'],
      young:    ['じこしょうかい！マジ緊張するー！','自己紹介ってやつ？やるよ！'],
      blunt:    ['自己紹介する。短めに。','じゃあ、自己紹介。'],
    },
    choices: ['私の名前は〇〇です (ฉันชื่อ...)','タイから来ました (มาจากไทย)','日本語を勉強しています (กำลังเรียนญี่ปุ่น)','よろしくお願いします！(ฝากตัวด้วยนะ)'],
    responses: {
      '私の名前は〇〇です (ฉันชื่อ...)': {
        friendly: ['わあ！素敵な名前ですね！🌸 ชื่อสวยมากเลยค่ะ！','いい名前ですね！覚えました！'],
        formal:   ['〇〇さんですね。よろしくお願いします。','ご丁寧にありがとうございます。'],
        shy:      ['あ...いい名前ですね... (ยิ้มเบาๆ)','そうですか...よろしくお願いします... 😊'],
        energetic:['わあー！！いい名前！！🎉 覚えたよ！！','〇〇さんね！！かわいい名前！！'],
        cool:     ['わかった。〇〇ね。','ああ、そう。'],
        old:      ['いい名前ですねえ。親が付けてくれた名前は大切にしなさいよ','〇〇さんか。覚えましたよ。'],
        young:    ['〇〇！？やば！かっこいい名前じゃん！','〇〇ね！覚えた！'],
        blunt:    ['わかった。〇〇ね。','ああ。次は？'],
      },
      'タイから来ました (มาจากไทย)': {
        friendly: ['タイから！？🇹🇭 わあ！タイ料理大好き！トムヤムクン食べたい！！','タイ！素晴らしい！バンコクですか？行ってみたい！'],
        formal:   ['タイからいらしたのですか。素晴らしい国ですね。','タイ料理は美味しいですよね。私も好きです。'],
        shy:      ['タイ...！遠いですね... すごいなあ... 😳','タイから来たんですか？タイ料理好きです...'],
        energetic:['タイ！！！🇹🇭🇹🇭 やばい！！行きたかったとこ！！','タイ！！！マジ！！！トムヤムクン食べたい！！！'],
        cool:     ['タイか。いいね。','ああ、タイね。'],
        old:      ['タイからはるばる来たんですか。遠かったでしょう。','タイは良い国ですよ。ご飯が美味しいって聞きました。'],
        young:    ['タイ！！やばくない！？遊びに行きたい！','タイ人なの！？すごっ！'],
        blunt:    ['タイか。わかった。','ふーん。タイね。'],
      },
      '日本語を勉強しています (กำลังเรียนญี่ปุ่น)': {
        friendly: ['すごい！日本語上手ですよ！🌸 どのくらい勉強してるんですか？','えらい！日本語勉強してるの！応援します！'],
        formal:   ['日本語を勉強されているのですか。素晴らしいですね。','ご努力が伝わります。続けてください。'],
        shy:      ['日本語...勉強してるんですか... すごい...私も頑張ってます...','上手ですよ...本当に...'],
        energetic:['えー！！すごい！！日本語上手！！🎉 もっと話して！！','一緒に練習しよ！！'],
        cool:     ['ふーん。上手だね。','そう。続けて。'],
        old:      ['日本語を勉強してるの。えらいですねえ。','いや、本当にすごいですよ。日本語は難しいのに。'],
        young:    ['日本語勉強してんの！？マジ！？すごくない！？','え！日本語上手じゃん！'],
        blunt:    ['上手だな。続けろ。','ああ。まあまあじゃないか。'],
      },
      'よろしくお願いします！(ฝากตัวด้วยนะ)': {
        friendly: ['こちらこそ！よろしくお願いします！🌸 仲良くしましょうね！','よろしく！これからよく話しましょうね！'],
        formal:   ['こちらこそ、どうぞよろしくお願いいたします。','よろしくお願いします。何かあればお気軽に。'],
        shy:      ['こ...こちらこそ...よろしくお願いします... 😊','よろしくお願いします... (โค้งหัว)'],
        energetic:['こちらこそーー！！🎉 よろしく！！絶対仲良くなろう！！','もう友達だよ！！'],
        cool:     ['ああ。よろしく。','こちらこそ。'],
        old:      ['こちらこそよろしくお願いします。若い人と話すのは楽しいですよ','よろしくね。何でも聞いてください。'],
        young:    ['よろしくーー！！SNSは？','よろしく！友達になろう！'],
        blunt:    ['ああ。よろしく。','こちらこそ。'],
      },
    },
    followups: {
      friendly: ['日本語はどこで勉強してますか？เรียนที่ไหนคะ？','趣味は何ですか？งานอดิเรกคืออะไรคะ？'],
      formal:   ['どのくらい日本語を勉強されていますか？','日本に来られたのはいつですか？'],
      shy:      ['あの...好きな食べ物は...何ですか...？','もし良ければ...趣味を教えてください...'],
      energetic:['好きなアニメは！！？','日本のどこが好き！！？'],
      cool:     ['趣味は？','何が好き？'],
      old:      ['日本に来たことはありますか？','ご家族は何人ですか？'],
      young:    ['好きなアニメある？','推しは？'],
      blunt:    ['趣味は？','好きな食べ物は？'],
    }
  },

  shopping: {
    name:'🛍️ ช้อปปิ้ง',
    opener: {
      friendly: ['いらっしゃいませ！🛍️ ยินดีต้อนรับค่ะ！何かお探しですか？','ようこそ！何かご用はありますか？😊'],
      formal:   ['いらっしゃいませ。ご用件をお聞かせください。','いらっしゃいませ。どのようなものをお探しですか？'],
      shy:      ['い...いらっしゃいませ... ご用件は...？','いらっしゃいませ... 何かお探しですか...？'],
      energetic:['いらっしゃいませー！！🎉 今日は何を探してるの！？','ようこそーー！！何が欲しいの！！？'],
      cool:     ['いらっしゃい。何が要る？','用件は？'],
      old:      ['いらっしゃい。どんなものをお探しかな？','ゆっくり見ていってください。'],
      young:    ['いらっしゃいませー！今日セール中だよ！','何探してる？'],
      blunt:    ['いらっしゃい。何が要る？はっきり言って。','用件は？'],
    },
    choices: ['これはいくらですか？(อันนี้เท่าไหร่)','ちょっと見てもいいですか？(ขอดูได้ไหม)','これをください (ขออันนี้)','もっと安いのはありますか？(มีถูกกว่าไหม)'],
    responses: {
      'これはいくらですか？(อันนี้เท่าไหร่)': {
        friendly: ['これは1,500円になります！🛍️ お安くなってますよ！','今、こちらは1,200円でございます！'],
        formal:   ['こちらは1,500円でございます。','税込みで1,620円となっております。'],
        shy:      ['え...えーと...これは...1,000円です... (ดูป้ายราคา)','こ...こちらは1,500円です...'],
        energetic:['1,500円！！安くない！！？セール中だよ！！','これ！1,000円ぽっきり！！やばくない！！'],
        cool:     ['1,500円。','これは1,000円。'],
        old:      ['これはね、1,500円ですよ。昔はもっと高かったんだが','1,500円。良いものですよ。'],
        young:    ['1,500円！安くない？','これ1,000円！買いじゃん！'],
        blunt:    ['1,500円。','1,000円だ。それだけ。'],
      },
      'ちょっと見てもいいですか？(ขอดูได้ไหม)': {
        friendly: ['もちろんです！ゆっくり見てくださいね！😊','どうぞどうぞ！何かあれば呼んでくださいね！'],
        formal:   ['はい、どうぞご覧ください。','ごゆっくりどうぞ。'],
        shy:      ['は...はい...どうぞ...ゆっくり見てください... 😊','もちろんです...お気軽に...'],
        energetic:['もちろん！！全部見てって！！🎉 いいのいっぱいあるよ！！','どうぞどうぞーー！何でも試着できるよ！！'],
        cool:     ['どうぞ。','ああ。好きに見て。'],
        old:      ['もちろんよ。ゆっくり見ていってください。','どうぞどうぞ。急がなくていいですよ。'],
        young:    ['もちろん！気に入ったの教えて！','どうぞー！新商品もあるよ！'],
        blunt:    ['どうぞ。','好きに見て。'],
      },
      'これをください (ขออันนี้)': {
        friendly: ['ありがとうございます！💕 袋に入れますか？','毎度ありがとうございます！ポイントカードはお持ちですか？'],
        formal:   ['ありがとうございます。こちらでよろしいでしょうか？','かしこまりました。'],
        shy:      ['あ...ありがとうございます... 袋はいりますか...？','は...はい。ありがとうございます... 😊'],
        energetic:['やったー！！ありがとうございます！！🎉 絶対気に入ると思う！！','ありがとうございます！！センスいいね！！'],
        cool:     ['わかった。袋いる？','ああ。1,500円。'],
        old:      ['ありがとうね。大切に使ってくださいよ。','毎度ありがとう。喜んでくれると嬉しいわ。'],
        young:    ['やったー！ありがとうございます！おしゃれ！','ありがとうございます！映えるね！'],
        blunt:    ['1,500円。','レシートいる？'],
      },
      'もっと安いのはありますか？(มีถูกกว่าไหม)': {
        friendly: ['はい！こちらはいかがですか？800円でお買い得ですよ！😊','セール品ならこちらが500円で！'],
        formal:   ['こちらはより手頃な価格でございます。800円となっております。','お値打ち品でしたら、こちらをご覧ください。'],
        shy:      ['えと...こちらは...800円のがありますが... 😊','もう少し安い...800円のもあります...'],
        energetic:['あるよ！！こっちの800円の！！超お得！！🎉','500円のもあるよ！！見て見て！！'],
        cool:     ['800円のがある。こっち。','安いのはあそこ。'],
        old:      ['あーそうねえ、こちらは800円だよ。こっちの方がいいかも','安いのも良いものありますよ。こちらはいかがですか？'],
        young:    ['あるよ！こっちの800円！お得じゃん！','安い系なら向こうのコーナー！'],
        blunt:    ['800円のがある。それだけ。','安いのはあそこ。終わり。'],
      },
    },
    followups: {
      friendly: ['他に何かお探しですか？','ポイントカードはお持ちですか？'],
      formal:   ['他にご用はございますか？','領収書はご入用ですか？'],
      shy:      ['他に...何かご入用ですか...？','袋はご入用でしょうか...？'],
      energetic:['他に何か欲しいものある！？','セール品もっと見る！？'],
      cool:     ['他は？','以上？'],
      old:      ['他に何か必要なものはありますか？','また来てくださいね。'],
      young:    ['他にも見る？','会計行く？'],
      blunt:    ['他は？','以上か？'],
    }
  },

  food: {
    name:'🍜 อาหาร',
    opener: {
      friendly: ['いらっしゃいませ！🍜 ご注文はお決まりですか？','ようこそ！今日のおすすめは...！'],
      formal:   ['いらっしゃいませ。ご注文はお決まりでしょうか？','本日のお席にご案内いたします。'],
      shy:      ['い...いらっしゃいませ... ご注文は...？','ようこそ...ご注文をどうぞ...'],
      energetic:['いらっしゃいませー！！🎉 今日のおすすめ聞きますか！？','ようこそーー！お腹すいてる！？'],
      cool:     ['いらっしゃい。注文は？','何にする？'],
      old:      ['いらっしゃいませ。ゆっくり選んでいってください。','どうぞどうぞ。今日は美味しいものがたくさんありますよ。'],
      young:    ['いらっしゃいませー！今日も美味しいよ！','何食べる？おすすめ聞く？'],
      blunt:    ['いらっしゃい。注文は？','メニュー見た？何にする？'],
    },
    choices: ['ラーメンをください (ขอราเมน)','おすすめは何ですか？(อะไรแนะนำ)','いただきます！(ขอรับประทาน)','ごちそうさまでした (ขอบคุณสำหรับอาหาร)'],
    responses: {
      'ラーメンをください (ขอราเมน)': {
        friendly: ['かしこまりました！🍜 少々お待ちください！辛さはいかがですか？','ラーメンですね！すぐお持ちします！'],
        formal:   ['かしこまりました。少々お待ちいただけますか。','ラーメン、一つでよろしかったでしょうか？'],
        shy:      ['は...はい...ラーメンですね... 少し...お待ちください...','かしこまりました... すぐ作ります...'],
        energetic:['ラーメン！！了解！！🎉 うちのラーメン絶対美味しいよ！！','ラーメンね！！まかせて！！すぐ持ってくる！！'],
        cool:     ['ラーメン。わかった。','了解。'],
        old:      ['ラーメンね。うちの自慢の一品ですよ。少し待ってくださいよ','はいはい。ラーメンね。おいしくしますよ。'],
        young:    ['ラーメン！了解です！うちのラーメンやばいよ！','ラーメンね！すぐ！'],
        blunt:    ['ラーメン。わかった。待て。','了解。少し待て。'],
      },
      'おすすめは何ですか？(อะไรแนะนำ)': {
        friendly: ['今日のおすすめは特製ラーメンです！🌟 スープが絶品ですよ！','こちらの照り焼きチキンがおすすめです！'],
        formal:   ['本日のおすすめは特製ラーメンでございます。','シェフのおすすめはこちらの定食です。'],
        shy:      ['え...おすすめ...は...ラーメンです...美味しいですよ...','おすすめは...照り焼き...です... 😊'],
        energetic:['おすすめ！！ラーメン！！絶対美味しい！！🎉 後悔しない！！','今日のおすすめはこれ！！マジやばい！！'],
        cool:     ['ラーメンがいい。','照り焼きチキン。はずれなし。'],
        old:      ['うちの自慢はラーメンですよ。昔からずっと変わらないレシピで...','照り焼きがいいですよ。体にも良いしね。'],
        young:    ['ラーメン！絶対！やばいよ！','照り焼き！映えるし美味しいし！'],
        blunt:    ['ラーメン。間違いない。','照り焼き。以上。'],
      },
      'いただきます！(ขอรับประทาน)': {
        friendly: ['どうぞ召し上がれ！🍜 ゆっくり楽しんでくださいね！','いただきます！って言えたんですね！素敵！'],
        formal:   ['どうぞ、ごゆっくりお召し上がりください。','ご用の際はお呼びください。'],
        shy:      ['どうぞ...ゆっくり食べてください... 😊','ゆっくり...楽しんでいってください...'],
        energetic:['いただきます！！最高！！🎉 美味しく食べてね！！','いただきます！！日本語上手！！'],
        cool:     ['どうぞ。','ゆっくり。'],
        old:      ['どうぞどうぞ。ゆっくり食べなさいよ。','召し上がれ。昔からこのレシピなんですよ。'],
        young:    ['いただきます！言えた！えらい！','どうぞ！食べて食べて！'],
        blunt:    ['どうぞ。','食え。'],
      },
      'ごちそうさまでした (ขอบคุณสำหรับอาหาร)': {
        friendly: ['ありがとうございます！💕 お味はいかがでしたか？','嬉しい！またいつでも来てくださいね！'],
        formal:   ['ありがとうございました。またのご来店をお待ちしております。','お粗末様でした。'],
        shy:      ['ありがとうございます... また来てください... 😊','お粗末様でした... また...どうぞ...'],
        energetic:['ごちそうさま！！ありがとう！！🎉 また来てね！！絶対！！','ありがとうございます！！また来てー！！'],
        cool:     ['またどうぞ。','ありがとう。'],
        old:      ['ありがとうね。体に気をつけてくださいよ。またいつでもどうぞ','美味しかったですか？嬉しいですよ。また来てくださいな。'],
        young:    ['ありがとうございます！またきてね！','ごちそうさまでした！また！'],
        blunt:    ['ありがとう。','またどうぞ。'],
      },
    },
    followups: {
      friendly: ['お飲み物はいかがですか？','デザートもありますよ！'],
      formal:   ['お飲み物はいかがでしょうか？','他にご注文はございますか？'],
      shy:      ['お...お飲み物は...いかがですか...？','デザート...はいかがでしょうか...'],
      energetic:['飲み物は！？！？','デザートも食べてって！！'],
      cool:     ['飲み物は？','デザートいる？'],
      old:      ['お茶でも飲みますか？','何か飲みますか？'],
      young:    ['ドリンクは？','デザートどう？'],
      blunt:    ['飲み物は？','デザートいる？'],
    }
  },

  direction: {
    name:'🗺️ เดินทาง',
    opener: {
      friendly: ['あの...すみません！🗺️ 道に迷っているんですが...','すみません！ちょっと聞いてもいいですか？'],
      formal:   ['恐れ入りますが、道を教えていただけますか？','すみません、少しよろしいでしょうか？'],
      shy:      ['あ...あの...すみません...道を聞いてもいいですか...？','す...すみません... 迷子みたいで...'],
      energetic:['すみませーん！！道に迷った！！助けてー！！','ちょっとちょっと！！道わかんなくて！！'],
      cool:     ['すみません。駅どこですか？','道聞いていいですか？'],
      old:      ['すみませんよ。道に迷ってしまってね...','ちょっとよろしいかな？'],
      young:    ['ちょっとすみません！道わかんなくて！','迷子なんですけど！助けてください！'],
      blunt:    ['すみません。駅どこですか？','ここどこですか？'],
    },
    choices: ['駅はどこですか？(สถานีอยู่ที่ไหน)','トイレはどこですか？(ห้องน้ำอยู่ที่ไหน)','まっすぐ行けばいいですか？(ตรงไปเลยไหม)','どのくらいかかりますか？(ใช้เวลานานไหม)'],
    responses: {
      '駅はどこですか？(สถานีอยู่ที่ไหน)': {
        friendly: ['駅ですか！🗺️ まっすぐ行って、右に曲がってください！5分くらいです！','あ、駅ですね！ここから歩いて10分くらいですよ！'],
        formal:   ['駅でしたら、この道をまっすぐ進んでいただき、最初の信号を右折してください。','駅は徒歩約10分ほどでございます。'],
        shy:      ['え...駅...ですか... まっすぐ行って... 右に... 曲がってください...','駅は...あっちの方向に...10分くらい歩きます...'],
        energetic:['駅！！まっすぐ行って右！！5分！！わかった！！？','すぐだよ！！山手線で3駅！！'],
        cool:     ['まっすぐ行って右。5分。','あそこ。10分。'],
        old:      ['駅ね。ここをまっすぐ行って、角を右に曲がりなさい。10分くらいかね','まっすぐ行って右ですよ。'],
        young:    ['駅！まっすぐ行って右！5分くらい！','駅ならあっちだよ！10分かな！'],
        blunt:    ['まっすぐ右。5分。','あそこ。10分。それだけ。'],
      },
      'トイレはどこですか？(ห้องน้ำอยู่ที่ไหน)': {
        friendly: ['トイレですか！😊 あそこに見えますよ！あの建物の中です！','すぐそこです！あの角を曲がったところに！'],
        formal:   ['お手洗いでしたら、あちらの建物内にございます。','こちらの廊下を進んでいただいたところにございます。'],
        shy:      ['え...トイレ...ですか... あそこに...あります... 😊','トイレは...あの建物の中です...'],
        energetic:['トイレ！！あそこ！！すぐそこ！！🎉','あの角曲がったとこ！！急いで！！'],
        cool:     ['あそこ。','あの建物の中。'],
        old:      ['トイレかね。あそこにあるよ。見えますか？','あそこの建物に入ったら右手にありますよ。'],
        young:    ['トイレ！あそこ！はよ！','あの建物入ってすぐ！'],
        blunt:    ['あそこ。','あの建物。以上。'],
      },
      'まっすぐ行けばいいですか？(ตรงไปเลยไหม)': {
        friendly: ['そうです！まっすぐ行って、左に曲がってください！🗺️','はい！まっすぐで合ってます！もう少しですよ！'],
        formal:   ['はい、そのままお進みください。しばらくしたら右折になります。','まっすぐで正解です。'],
        shy:      ['は...はい...まっすぐ...で合ってます... (ชี้ทาง)','そうです...まっすぐ行って...えっと...左です...'],
        energetic:['そう！！まっすぐ！！あとちょっと！！頑張れ！！','まっすぐで合ってる！！もうすぐだよ！！'],
        cool:     ['ああ。まっすぐ。その後右。','そう。まっすぐ。'],
        old:      ['そうですよ。まっすぐ行って、左ですよ','まっすぐで合ってますよ。もう少しです。'],
        young:    ['そう！まっすぐ！その後左！','合ってる！もうすぐ！'],
        blunt:    ['まっすぐ。その後右。','そう。まっすぐ。'],
      },
      'どのくらいかかりますか？(ใช้เวลานานไหม)': {
        friendly: ['歩いて10分くらいです！🚶 でも電車なら3駅ですよ！','そんなに遠くないですよ！15分くらいです！'],
        formal:   ['徒歩でおよそ10分ほどかと存じます。','電車をご利用でしたら、3駅になります。'],
        shy:      ['えと...10分...くらい...だと思います...','15分...くらい...かな...自信ないですが...'],
        energetic:['10分！！歩けば！！でも走れば5分！！頑張れ！！','15分くらい！近い近い！！'],
        cool:     ['10分。','15分。電車なら5分。'],
        old:      ['歩いて10分くらいかね。ゆっくり行きなさい。','15分はかからないよ。'],
        young:    ['10分くらい！近いよ！','15分！急げば10分！'],
        blunt:    ['10分。','15分。以上。'],
      },
    },
    followups: {
      friendly: ['他に分からないことはありますか？','観光ですか？良い旅を！'],
      formal:   ['他にご不明な点はございますか？','お気をつけて。'],
      shy:      ['わかりましたか...？他に...何か聞きたいことは...？','大丈夫...ですか...？'],
      energetic:['他にわからないとこある！？！？','楽しんでね！！'],
      cool:     ['以上？','気をつけて。'],
      old:      ['他に迷っているところはありますか？','気をつけていきなさいよ。'],
      young:    ['他にもある？','気をつけてね！'],
      blunt:    ['他は？','以上。'],
    }
  },

  school: {
    name:'📚 โรงเรียน',
    opener: {
      friendly: ['こんにちは！📚 今日も授業頑張りましょうね！','同じクラスなんですね！よろしく！'],
      formal:   ['本日の授業についてですが...','よろしくお願いします。一緒に勉強しましょう。'],
      shy:      ['あ...同じクラスですね... よろしく... 😊','こんにちは... 隣に座っていいですか...？'],
      energetic:['こんにちは！！📚 一緒に勉強しよう！！🎉','同じクラスだ！！やった！！'],
      cool:     ['ああ。同じクラスか。','よろしく。'],
      old:      ['みなさん、授業を始めますよ。','今日もしっかり学びましょう'],
      young:    ['同じクラス！やばっ！！','一緒に授業受けようよ！'],
      blunt:    ['同じクラスか。よろしく。','授業始まるぞ。'],
    },
    choices: ['今日の授業は何ですか？(วันนี้เรียนอะไร)','宿題を教えてもらえますか？(ช่วยบอกการบ้านด้วย)','試験はいつですか？(สอบเมื่อไหร่)','一緒に勉強しませんか？(เรียนด้วยกันไหม)'],
    responses: {
      '今日の授業は何ですか？(วันนี้เรียนอะไร)': {
        friendly: ['今日は数学と英語ですよ！📚 一緒に頑張りましょう！','今日は理科の実験があるんです！楽しいですよ！'],
        formal:   ['本日は数学、英語、そして理科の予定です。','時間割によりますと、午前中は数学です。'],
        shy:      ['えと...今日は...数学と...英語...だと思います...','あの...確か...理科も...あった気が...'],
        energetic:['数学！英語！理科！！全部！！頑張ろう！！🎉','今日は実験もある！！わくわく！！'],
        cool:     ['数学と英語。','理科もある。'],
        old:      ['今日は数学から始まります。しっかり聞いてください。','授業は数学、英語の順ですよ。'],
        young:    ['数学と英語！眠い！','理科！実験あるよ！'],
        blunt:    ['数学と英語。以上。','理科もある。それだけ。'],
      },
      '宿題を教えてもらえますか？(ช่วยบอกการบ้านด้วย)': {
        friendly: ['もちろん！📝 数学は10ページの問題です！英語は作文ですよ！','一緒にやりましょうか？放課後どう？'],
        formal:   ['宿題は数学の10ページと英語の作文です。','明日までに提出してください。'],
        shy:      ['え...宿題...数学の...10ページと...英語の...作文です...','あの...一緒に確認しましょうか...'],
        energetic:['宿題！！数学10ページ！英語作文！一緒にやろう！！🎉','ぜんぶ教えてあげる！！'],
        cool:     ['数学10ページ。英語作文。','明日まで。'],
        old:      ['宿題は数学の10ページです。しっかりやってきなさい。','英語の作文も忘れずに。'],
        young:    ['数学10ページ！英語作文！多い！','一緒にやる？放課後！'],
        blunt:    ['数学10ページ。英語作文。明日まで。','それだけ。'],
      },
      '試験はいつですか？(สอบเมื่อไหร่)': {
        friendly: ['来週の金曜日ですよ！😊 一緒に勉強しましょう！','試験は来週！準備は大丈夫ですか？'],
        formal:   ['試験は来週の金曜日に予定されています。','範囲は第3章から第5章までです。'],
        shy:      ['え...試験...来週の...金曜日...です... (กังวลนิดนึง)','来週...かな...範囲は...第3章から...'],
        energetic:['来週金曜！！一緒に勉強しよう！！絶対合格！！🎉','来週！！やばい！！頑張らなきゃ！！'],
        cool:     ['来週金曜。','範囲は3章から5章。'],
        old:      ['試験は来週の金曜日です。しっかり準備してきなさいよ。','範囲を間違えないようにね。'],
        young:    ['来週金曜！やばい！！勉強しなきゃ！','一緒に勉強しよう！'],
        blunt:    ['来週金曜。範囲は3章から5章。以上。','準備しろ。'],
      },
      '一緒に勉強しませんか？(เรียนด้วยกันไหม)': {
        friendly: ['もちろん！！🎉 いつにしましょうか？図書館はどう？','嬉しい！一緒に勉強しましょう！'],
        formal:   ['はい、ぜひ。放課後はいかがでしょうか。','図書館で勉強しましょうか。'],
        shy:      ['え...ほんとうに...いいんですか...？嬉しい... 😊','い...一緒に...いいんですか...？ありがとうございます...'],
        energetic:['もちろん！！！一緒にやろう！！🎉 絶対楽しい！！','やったー！！いつでも！！どこでも！！'],
        cool:     ['ああ。図書館で。','いいよ。放課後。'],
        old:      ['良いですね。勉強は一人よりみんなでする方が良いですよ。','図書館で会いましょう。'],
        young:    ['いいじゃん！！一緒にやろう！！','やろう！カフェとかどう？'],
        blunt:    ['いいよ。図書館。放課後。','ああ。やろう。'],
      },
    },
    followups: {
      friendly: ['どの教科が得意ですか？','好きな授業は何ですか？'],
      formal:   ['他に質問はありますか？','授業の予習はしてきましたか？'],
      shy:      ['あの...得意な教科は...何ですか...？','えっと...好きな授業は...？'],
      energetic:['得意な教科は！？一緒に教え合おう！！','趣味は何！？放課後遊ぼう！！'],
      cool:     ['得意な科目は？','他は？'],
      old:      ['勉強は毎日少しずつすることが大切ですよ。','困ったことがあれば聞きなさい。'],
      young:    ['好きな教科ある？','部活は？'],
      blunt:    ['得意科目は？','他にある？'],
    }
  },

  work: {
    name:'💼 ที่ทำงาน',
    opener: {
      friendly: ['おはようございます！💼 今日もよろしくお願いします！','お疲れ様です！今日はどうでしたか？'],
      formal:   ['おはようございます。本日もよろしくお願いいたします。','お疲れ様でございます。'],
      shy:      ['あ...おはようございます... よろしくお願いします... 😊','お...お疲れ様です...'],
      energetic:['おはようございます！！今日も頑張りましょう！！🎉','お疲れ！今日もやりきった！！'],
      cool:     ['おはよう。','お疲れ。'],
      old:      ['おはようございます。今日も一日しっかりやりましょう。','若い頃はもっと早く来ていたんだがね。'],
      young:    ['おはようございます！今日も頑張ろう！','お疲れです！！'],
      blunt:    ['おはよう。仕事始めよう。','お疲れ。報告は？'],
    },
    choices: ['会議は何時ですか？(ประชุมกี่โมง)','資料を送ってもらえますか？(ส่งเอกสารให้ด้วย)','お先に失礼します (ขอตัวก่อนนะ)','お疲れ様でした！(お疲れ様)'],
    responses: {
      '会議は何時ですか？(ประชุมกี่โมง)': {
        friendly: ['会議は3時からです！📋 準備はできていますか？','午後2時から会議室Bで始まりますよ！'],
        formal:   ['会議は本日15時からとなっております。','会議室Bにてお集まりください。'],
        shy:      ['えと...会議は...3時から...だと思います...','午後2時から...会議室B...です...'],
        energetic:['3時！！準備して！！絶対遅れないで！！','午後2時！会議室B！忘れないで！！'],
        cool:     ['3時。会議室B。','午後2時。'],
        old:      ['会議は3時からです。早めに行きなさい。','午後2時ですよ。'],
        young:    ['3時！会議室B！遅れないでよ！','午後2時だよ！'],
        blunt:    ['3時。会議室B。以上。','午後2時。終わり。'],
      },
      '資料を送ってもらえますか？(ส่งเอกสารให้ด้วย)': {
        friendly: ['もちろんです！📧 今すぐ送りますね！','はい！メールアドレスを教えてください！'],
        formal:   ['承知いたしました。すぐにお送りします。','メールアドレスをご確認ください。'],
        shy:      ['は...はい...今すぐ...送ります...','わかりました...すぐ送ります...'],
        energetic:['もちろん！！すぐ送る！！待ってて！！','了解！！今すぐ！！'],
        cool:     ['わかった。送る。','了解。'],
        old:      ['はい、送りますよ。メール確認しておいてください。','すぐ送ります。'],
        young:    ['了解！！今すぐ送る！','わかった！送るね！'],
        blunt:    ['わかった。送る。以上。','了解。すぐ送る。'],
      },
      'お先に失礼します (ขอตัวก่อนนะ)': {
        friendly: ['お疲れ様でした！💕 ゆっくり休んでくださいね！','お疲れさまでした！また明日！'],
        formal:   ['お疲れ様でした。お気をつけてお帰りください。','また明日よろしくお願いします。'],
        shy:      ['お...お疲れ様でした... 気をつけて...','またあした...お疲れ様でした...'],
        energetic:['お疲れー！！ゆっくり休んでね！！🎉 また明日！！','お疲れ！！明日も頑張ろう！！'],
        cool:     ['お疲れ。','また明日。'],
        old:      ['お疲れ様でした。無理せずにね。','お疲れ様。また明日。'],
        young:    ['お疲れー！ゆっくり休んでね！','お疲れ！また明日！'],
        blunt:    ['お疲れ。また明日。','以上。'],
      },
      'お疲れ様でした！(お疲れ様)': {
        friendly: ['お疲れ様でした！今日も一日頑張りましたね！😊','こちらこそお疲れ様でした！'],
        formal:   ['お疲れ様でございました。','こちらこそ、お疲れ様でした。'],
        shy:      ['お...お疲れ様でした... ありがとうございます...','こちらこそ...お疲れ様でした...'],
        energetic:['お疲れーーー！！今日もがんばった！！🎉','お疲れ！！明日も頑張ろう！！'],
        cool:     ['ああ。お疲れ。','こちらこそ。'],
        old:      ['お疲れ様でした。若い人は元気ですねえ。','こちらこそお疲れ様でした。'],
        young:    ['お疲れ！！明日も！','こちらこそー！'],
        blunt:    ['お疲れ。','こちらこそ。'],
      },
    },
    followups: {
      friendly: ['今日のランチはどこで食べましたか？','週末は何か予定がありますか？'],
      formal:   ['明日の予定はよろしいでしょうか？','他にご用件はございますか？'],
      shy:      ['あの...ランチ...一緒に食べますか...？','他に...何か...ありますか...？'],
      energetic:['ランチ一緒に行こう！！どこがいい！？','週末何してる！？'],
      cool:     ['ランチは？','週末は？'],
      old:      ['最近仕事はどうですか？','ご家族はお元気ですか？'],
      young:    ['ランチどこ行く？','週末遊ぼうよ！'],
      blunt:    ['ランチは？','週末は？'],
    }
  },

  hobby: {
    name:'🎮 งานอดิเรก',
    opener: {
      friendly: ['趣味の話しましょうか！🎮 何が好きですか？','趣味って大事ですよね！私はアニメが好きです！'],
      formal:   ['趣味についてお聞きしてもよろしいでしょうか。','ご趣味は何かお持ちですか？'],
      shy:      ['あの...趣味の話...してもいいですか...？','趣味...何がありますか...？'],
      energetic:['趣味！！何が好き！！！🎉 話して話して！！','趣味の話しよーー！！絶対楽しい！！'],
      cool:     ['趣味は？','何が好き？'],
      old:      ['趣味はお持ちですか？昔はよく釣りに行ったものですが','最近の若者の趣味は何なんですかね？'],
      young:    ['趣味何！？ゲームとか？アニメ？','趣味教えてよ！！'],
      blunt:    ['趣味は何？','好きなことは？'],
    },
    choices: ['アニメが好きです (ชอบอนิเมะ)','ゲームをします (เล่นเกม)','音楽を聴きます (ฟังเพลง)','旅行が好きです (ชอบท่องเที่ยว)'],
    responses: {
      'アニメが好きです (ชอบอนิเมะ)': {
        friendly: ['わあ！アニメ好きなんですね！🌸 何が好きですか？私も大好きです！','アニメ！いいですね！最近何を見てますか？'],
        formal:   ['アニメがお好きなんですね。最近は何をご覧になっていますか？','アニメは日本文化の一つですね。'],
        shy:      ['アニメ...好きなんですか...私も...好きです...','何のアニメが...好きですか...？'],
        energetic:['アニメ！！私も大好き！！🎉 推しは誰！？！？','アニメ仲間だー！！！どのアニメが一番好き！！'],
        cool:     ['ふーん。何が好き？推しは？','アニメか。'],
        old:      ['アニメですか。最近のはよく知らないがね...昔は鉄腕アトムを見たものだよ','楽しいんですかね？'],
        young:    ['アニメ！！やばい！！推しは！？','アニメ仲間！！何見てる！？'],
        blunt:    ['何のアニメ？','推しは誰？'],
      },
      'ゲームをします (เล่นเกม)': {
        friendly: ['ゲームですか！🎮 どんなゲームが好きですか？','RPGとか好きですか？一緒にやりましょうよ！'],
        formal:   ['ゲームをされるんですね。どのようなジャンルがお好みですか？','最近はeスポーツも注目されていますね。'],
        shy:      ['ゲーム...やるんですか...どんなゲームが...好きですか...？','私も...少しだけ...やります...'],
        energetic:['ゲーム！！私も！！🎉 一緒にやろう！！フレンドになって！！','ゲーマー仲間！！何のゲームやってる！？！？'],
        cool:     ['ゲームか。何やってる？','ジャンルは？'],
        old:      ['ゲームか...昔はそんなものなかったが...楽しそうですね','適度にしなさいよ'],
        young:    ['ゲーム！！やばい！！一緒にやろう！！','何のゲーム！？マルチできる？'],
        blunt:    ['何やってる？','ジャンルは？'],
      },
      '音楽を聴きます (ฟังเพลง)': {
        friendly: ['音楽！🎵 どんなジャンルが好きですか？J-POPとか？','音楽は心が落ち着きますよね！私もよく聴きます！'],
        formal:   ['音楽をお聴きになるんですね。どのようなジャンルがお好みですか？','音楽は心を豊かにしてくれますね。'],
        shy:      ['音楽...好きですか...私も好きです... 😊','どんな...音楽が...好きですか...？'],
        energetic:['音楽！！🎵 私もだいすき！！推しのアーティストは！？','音楽仲間！！J-POP？K-POP？どっち！？'],
        cool:     ['ジャンルは？','好きなアーティストは？'],
        old:      ['音楽か。昔は演歌をよく聴いたものです','最近の音楽は...よくわかりませんが...'],
        young:    ['音楽！！J-POP？K-POP？','推しは誰！？'],
        blunt:    ['ジャンルは？','好きなアーティストは？'],
      },
      '旅行が好きです (ชอบท่องเที่ยว)': {
        friendly: ['旅行！✈️ 素敵ですね！どこに行きましたか？','旅行大好き！一緒に旅行計画しましょうよ！'],
        formal:   ['旅行がお好きなんですね。どのような場所をご訪問されましたか？','日本国内外を旅されるんですか？'],
        shy:      ['旅行...好きなんですか...いいですね... 😊','どこに...行きましたか...？'],
        energetic:['旅行！！✈️ いいね！！どこ行ったの！！？一緒に計画しよ！！','旅行仲間！！次どこ行く！！？'],
        cool:     ['どこに行った？','好きな場所は？'],
        old:      ['旅行か。若い頃はよく行ったものですよ。','どこへ行ったんですか？いいですねえ。'],
        young:    ['旅行！！どこ行った！？映えるとこ？','次どこ行く？一緒に行こう！'],
        blunt:    ['どこに行った？','好きな場所は？'],
      },
    },
    followups: {
      friendly: ['他に趣味はありますか？','週末はよく何をしていますか？'],
      formal:   ['他にご趣味はお持ちですか？','休日はどのようにお過ごしですか？'],
      shy:      ['他に...趣味は...ありますか...？','週末は...何してますか...？'],
      energetic:['他の趣味は！！？一緒に何かしよう！！','週末何してる！？遊ぼう！！'],
      cool:     ['他の趣味は？','週末は？'],
      old:      ['他にはどんなことをされているんですか？','若い人はいろんなことをするんですねえ。'],
      young:    ['他の趣味は？','週末何してる？'],
      blunt:    ['他は？','週末は？'],
    }
  },

  weather: {
    name:'🌤️ อากาศ',
    opener: {
      friendly: ['今日はいい天気ですね！☀️ お出かけ日和ですよ！','天気の話、しましょうか！最近どうですか？'],
      formal:   ['本日はよいお天気でございますね。','お天気のお話でもよろしいでしょうか。'],
      shy:      ['今日は...いい天気ですね... 😊','天気...の話...しませんか...？'],
      energetic:['今日めっちゃ天気いい！！☀️☀️ 最高！！','天気サイコー！！外出よう！！'],
      cool:     ['いい天気だな。','天気の話か。'],
      old:      ['今日はよいお天気ですね。昔はこういう日に釣りに行ったものです','天気が良いと気分も良いですね。'],
      young:    ['今日天気よくない！？最高！','外行こうよ！天気いいし！'],
      blunt:    ['天気いいな。','で、何？'],
    },
    choices: ['今日は暑いですね (วันนี้ร้อนจัง)','雨が降りそうですか？(ฝนจะตกไหม)','明日の天気は？(พรุ่งนี้อากาศยังไง)','日本の冬は寒いですか？(ฤดูหนาวหนาวไหม)'],
    responses: {
      '今日は暑いですね (วันนี้ร้อนจัง)': {
        friendly: ['本当ですね！☀️ 熱中症に気をつけてくださいね！水分補給大事ですよ！','暑い！でも夏って感じがして私は好きです！'],
        formal:   ['そうですね。熱中症にはご注意ください。','今年の夏は特に暑いようですね。'],
        shy:      ['ほんとに...暑いですね... 気をつけてください...','暑い...ですね... 水...飲みましたか...？'],
        energetic:['暑い！！でも夏最高！！🌟 海に行こう！！','暑い暑い！！アイス食べよう！！'],
        cool:     ['ああ。暑いな。','水飲んで。'],
        old:      ['暑いですね。体に気をつけなさいよ。水分をしっかり取って。','昔はこんなに暑くなかったんだがね...'],
        young:    ['暑い！！アイス食べよう！！','海行こうよ！！'],
        blunt:    ['暑いな。水飲め。','ああ。暑い。'],
      },
      '雨が降りそうですか？(ฝนจะตกไหม)': {
        friendly: ['天気予報では午後から雨だそうですよ！🌂 傘持って行った方がいいですね！','空を見ると...降るかもしれませんね！'],
        formal:   ['天気予報によりますと、午後から降水の可能性があります。','傘をお持ちになった方がよろしいかと存じます。'],
        shy:      ['えと...天気予報では...午後から雨...かもしれません...','傘...持ってますか...？'],
        energetic:['降るかも！！傘持って！！🌂 でも雨もたまにはいいじゃん！！','天気予報じゃ午後雨！急いで！！'],
        cool:     ['午後から雨。傘持て。','降るかも。'],
        old:      ['天気予報では雨だそうですよ。傘を持っていきなさいよ。','昔は体で天気がわかったものだが...'],
        young:    ['雨降るって！傘持ってく！','午後雨かも！'],
        blunt:    ['午後雨。傘持て。','降るかも。以上。'],
      },
      '明日の天気は？(พรุ่งนี้อากาศยังไง)': {
        friendly: ['明日は晴れの予報ですよ！🌞 お出かけ日和ですね！','明日は曇りかもしれませんが、雨は降らないみたいです！'],
        formal:   ['明日は晴れの予報となっております。','明日は気温が下がる見込みです。'],
        shy:      ['明日は...晴れ...らしいです... 😊','えと...明日は...曇りかも...しれません...'],
        energetic:['明日晴れ！！🌞 どこか行こう！！遊ぼう！！','明日晴れるって！！最高！！'],
        cool:     ['晴れ。','曇り。'],
        old:      ['明日は晴れだそうですよ。良かった良かった。','天気が良いと気持ちも晴れますね。'],
        young:    ['明日晴れ！どこ行こう！','明日晴れるって！遊ぼう！'],
        blunt:    ['晴れ。以上。','曇り。'],
      },
      '日本の冬は寒いですか？(ฤดูหนาวหนาวไหม)': {
        friendly: ['日本の冬は結構寒いですよ！❄️ でも雪が降ると綺麗で大好きです！','地方によって全然違いますよ！北海道はすごく寒いです！'],
        formal:   ['地域によって異なりますが、全般的に冷え込みます。','北海道は特に寒く、東京は比較的温暖です。'],
        shy:      ['寒いです...特に北海道は...とても寒くて... 😊','でも...雪が綺麗で...好きです...'],
        energetic:['寒い！！❄️ でも雪は最高！！雪だるま作ろう！！','北海道とか超寒い！！でも楽しいよ！！'],
        cool:     ['寒い。北海道は特に。','地域による。'],
        old:      ['昔の冬はもっと寒かったんですよ。','北海道は本当に寒いよ。東京はまあまあかね。'],
        young:    ['寒い！！でも雪最高！！','北海道やばいくらい寒い！'],
        blunt:    ['寒い。北海道は特に。以上。','寒い。以上。'],
      },
    },
    followups: {
      friendly: ['好きな季節はありますか？','日本の四季を楽しんでいますか？'],
      formal:   ['お好みの季節はございますか？','日本の気候はいかがですか？'],
      shy:      ['好きな...季節は...ありますか...？','日本の天気は...どう思いますか...？'],
      energetic:['好きな季節は！？！？','夏と冬どっちが好き！？'],
      cool:     ['好きな季節は？','夏冬どっち？'],
      old:      ['日本の四季は美しいですよ。どの季節が好きですか？','昔は秋が一番好きだったんですよ。'],
      young:    ['好きな季節は？','夏？冬？'],
      blunt:    ['好きな季節は？','以上。'],
    }
  },

  transport: {
    name:'🚃 ขนส่ง',
    opener: {
      friendly: ['電車に乗るんですか！🚃 どこまで行きますか？','交通の話しましょう！東京の電車は複雑ですよね！'],
      formal:   ['交通機関についてお伺いしてもよろしいでしょうか。','どちらまでいらっしゃいますか？'],
      shy:      ['あの...電車...ですか...どこまで行きますか...？','交通...の話...してもいいですか...？'],
      energetic:['電車！！🚃 どこ行くの！！一緒に行こう！！','交通の話！！東京の電車やばいよね！！'],
      cool:     ['どこまで？','電車か。'],
      old:      ['電車ですか。昔は路面電車が走っていたんだがね...','どちらまで行かれますか？'],
      young:    ['電車？どこ行くの？','一緒に行こう！'],
      blunt:    ['どこまで？','用件は？'],
    },
    choices: ['〇〇駅まで行きたいです (อยากไปสถานี...)','切符の買い方を教えてください (สอนซื้อตั๋วด้วย)','終電は何時ですか？(รถไฟสายสุดท้ายกี่โมง)','バスで行けますか？(ไปด้วยรถบัสได้ไหม)'],
    responses: {
      '〇〇駅まで行きたいです (อยากไปสถานี...)': {
        friendly: ['〇〇駅ですね！🚃 山手線に乗って3駅ですよ！一緒に行きましょうか？','〇〇駅なら、ここから歩いて2分の駅から乗れますよ！'],
        formal:   ['〇〇駅でしたら、山手線をご利用ください。3駅になります。','こちらの駅から乗り換えなしで行けます。'],
        shy:      ['〇〇駅...ですね...山手線に乗って...3駅です...','こっちの線に乗って...3駅です...'],
        energetic:['〇〇駅！！山手線！！3駅！！わかった！！？','すぐだよ！！3駅！！'],
        cool:     ['山手線。3駅。','3駅。以上。'],
        old:      ['〇〇駅ねえ。山手線に乗って3駅ですよ。','山手線で行けますよ。3駅です。'],
        young:    ['山手線で3駅！近いよ！','〇〇駅ね！山手線！'],
        blunt:    ['山手線。3駅。以上。','3駅。'],
      },
      '切符の買い方を教えてください (สอนซื้อตั๋วด้วย)': {
        friendly: ['もちろんですよ！😊 あの機械で買います！まず行き先を押して、お金を入れるんです！','一緒に買いましょうか！ついて来てください！'],
        formal:   ['券売機でお買い求めください。目的地を選択し、金額を投入してください。','ICカードのご利用もお勧めします。'],
        shy:      ['あの...あの機械で...目的地を押して...お金を入れて...','ICカードを...使うと...便利ですよ...'],
        energetic:['教えてあげる！！一緒に買おう！！🎉 あの機械！目的地押して！！','簡単！！一緒にやってみよう！！'],
        cool:     ['あの機械で。目的地選んで金入れろ。','ICカード使え。楽だから。'],
        old:      ['あれを押して行き先を選んでお金を入れるんですよ。ICカードというものを作れば便利ですよ。','昔は駅員さんに言えば買ってくれたんだがね...'],
        young:    ['あの機械！簡単だよ！行き先押してお金入れるだけ！','ICカード作ったほうがいいよ！'],
        blunt:    ['あの機械。行き先押して金入れろ。以上。','ICカード使え。'],
      },
      '終電は何時ですか？(รถไฟสายสุดท้ายกี่โมง)': {
        friendly: ['終電は大体12時くらいですよ！🚃 気をつけてくださいね！','路線によって違いますが、だいたい深夜12時前後です！'],
        formal:   ['路線によって異なりますが、概ね深夜12時頃が最終電車となります。','事前にご確認されることをお勧めします。'],
        shy:      ['終電は...12時くらい...だと思います...路線によって...違うかも...','確認した方が...いいかもしれません...'],
        energetic:['終電12時！！遅くなったらタクシーだよ！！','深夜12時！！気をつけて！！'],
        cool:     ['だいたい12時。路線による。','確認しろ。'],
        old:      ['終電は12時ごろだね。乗り遅れないようにしなさいよ。','昔はもっと早かったんだが...'],
        young:    ['12時くらい！乗り遅れないで！','路線によるけど12時！'],
        blunt:    ['12時。路線による。確認しろ。','12時。以上。'],
      },
      'バスで行けますか？(ไปด้วยรถบัสได้ไหม)': {
        friendly: ['バスでも行けますよ！🚌 でも電車の方が速いですよ！','あのバス停から乗れますよ！20分くらいです！'],
        formal:   ['バスのご利用も可能です。ただし電車の方が所要時間が少のうございます。','バス停はこちらからすぐのところにございます。'],
        shy:      ['バスでも...行けます...でも電車の方が...早いかも...','あそこのバス停から...乗れます...'],
        energetic:['バスも行ける！！でも電車の方が速い！！','あそこのバス停！20分！でも電車の方が楽！！'],
        cool:     ['行ける。でも電車の方が速い。','バス停はあそこ。'],
        old:      ['バスでも行けますよ。でも時間がかかりますね。電車の方が便利ですよ。','昔はバスばかりだったんですが'],
        young:    ['バスでも行ける！でも電車の方が速い！','あのバス停から！でも電車がおすすめ！'],
        blunt:    ['行ける。でも遅い。電車の方がいい。','バス停はあそこ。'],
      },
    },
    followups: {
      friendly: ['電車は分かりましたか？','他に行きたいところはありますか？'],
      formal:   ['他にご不明な点はございますか？','ご安全にお気をつけてお越しください。'],
      shy:      ['わかりましたか...？他に...何か聞きたいことは...？','大丈夫...ですか...？'],
      energetic:['わかった！？他にどこ行くの！？','一緒に行こう！！'],
      cool:     ['わかった？','他は？'],
      old:      ['わかりましたか？困ったらまた聞いてください。','気をつけていきなさいよ。'],
      young:    ['わかった？他に行くとこある？','一緒に行こうよ！'],
      blunt:    ['わかったか？','他は？'],
    }
  },
};